import '../models/product_model.dart';

final List<Product> dummyProductsSeed = [
  // PART 1 — GROCERY & KITCHEN PRODUCTS
  // Subcategory: Vegetables & Fruits (fruits_veg)
  Product(
    id: 'gk_fv_1',
    name: 'Fresh Tomatoes',
    brand: 'Fresh Farm',
    category: 'grocery_kitchen',
    subcategory: 'fruits_veg',
    description: 'Juicy organic tomatoes.',
    images: ['https://images.unsplash.com/photo-1595855759920-86582396756a?w=500&auto=format&fit=crop&q=60'],
    tags: ['tomato', 'vegetable', 'fresh'],
    price: 45.0,
    mrp: 60.0,
    rating: 4.8,
    discount: 25,
    stock: 50,
    reviewCount: 380,
    isDeal: true,
    isBestSeller: true,
    weight: '500',
    unit: 'g',
  ),
  Product(
    id: 'gk_fv_2',
    name: 'Green Capsicum',
    brand: 'Fresh Farm',
    category: 'grocery_kitchen',
    subcategory: 'fruits_veg',
    description: 'Crunchy green bell peppers.',
    images: ['https://images.unsplash.com/photo-1588612140417-640a43b4f6ef?w=500&auto=format&fit=crop&q=60'],
    tags: ['capsicum', 'peppers', 'vegetable'],
    price: 30.0,
    mrp: 35.0,
    rating: 4.6,
    discount: 14,
    stock: 40,
    reviewCount: 210,
    isDeal: false,
    isBestSeller: false,
    weight: '250',
    unit: 'g',
  ),
  Product(
    id: 'gk_fv_3',
    name: 'Baby Spinach',
    brand: 'Organic Greens',
    category: 'grocery_kitchen',
    subcategory: 'fruits_veg',
    description: 'Tender baby spinach leaves.',
    images: ['https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=500&auto=format&fit=crop&q=60'],
    tags: ['spinach', 'greens', 'leaves'],
    price: 25.0,
    mrp: 30.0,
    rating: 4.7,
    discount: 16,
    stock: 30,
    reviewCount: 154,
    isDeal: false,
    isBestSeller: true,
    weight: '100',
    unit: 'g',
  ),
  Product(
    id: 'gk_fv_4',
    name: 'Red Onions',
    brand: 'Fresh Farm',
    category: 'grocery_kitchen',
    subcategory: 'fruits_veg',
    description: 'Crisp red onions.',
    images: ['https://images.unsplash.com/photo-1618512417740-9755f1fde1b0?w=500&auto=format&fit=crop&q=60'],
    tags: ['onion', 'vegetable', 'red onion'],
    price: 35.0,
    mrp: 40.0,
    rating: 4.5,
    discount: 12,
    stock: 120,
    reviewCount: 890,
    isDeal: false,
    isBestSeller: true,
    weight: '1',
    unit: 'kg',
  ),
  Product(
    id: 'gk_fv_5',
    name: 'Broccoli',
    brand: 'Fresh Farm',
    category: 'grocery_kitchen',
    subcategory: 'fruits_veg',
    description: 'Nutritious green broccoli florets.',
    images: ['https://images.unsplash.com/photo-1453224311646-39a79720436d?w=500&auto=format&fit=crop&q=60'],
    tags: ['broccoli', 'vegetable', 'greens'],
    price: 60.0,
    mrp: 80.0,
    rating: 4.6,
    discount: 25,
    stock: 25,
    reviewCount: 120,
    isDeal: true,
    isBestSeller: false,
    weight: '1',
    unit: 'pc',
  ),
  Product(
    id: 'gk_fv_6',
    name: 'Yellow Banana',
    brand: 'Fresh Farm',
    category: 'grocery_kitchen',
    subcategory: 'fruits_veg',
    description: 'Sweet yellow robusta bananas.',
    images: ['https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=500&auto=format&fit=crop&q=60'],
    tags: ['banana', 'fruit', 'sweet'],
    price: 45.0,
    mrp: 50.0,
    rating: 4.8,
    discount: 10,
    stock: 100,
    reviewCount: 940,
    isDeal: false,
    isBestSeller: true,
    weight: '1',
    unit: 'kg',
  ),

  // Subcategory: Atta Rice & Dal (atta_rice_dal)
  Product(
    id: 'gk_ard_1',
    name: 'Aashirvaad Wheat Atta 5kg',
    brand: 'Aashirvaad',
    category: 'grocery_kitchen',
    subcategory: 'atta_rice_dal',
    description: '100% whole wheat flour.',
    images: ['https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500&auto=format&fit=crop&q=60'],
    tags: ['atta', 'flour', 'wheat', 'aashirvaad'],
    price: 245.0,
    mrp: 270.0,
    rating: 4.8,
    discount: 9,
    stock: 45,
    reviewCount: 2310,
    isDeal: false,
    isBestSeller: true,
    weight: '5',
    unit: 'kg',
  ),
  Product(
    id: 'gk_ard_2',
    name: 'India Gate Basmati Rice 1kg',
    brand: 'India Gate',
    category: 'grocery_kitchen',
    subcategory: 'atta_rice_dal',
    description: 'Premium long grain basmati rice.',
    images: ['https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500&auto=format&fit=crop&q=60'],
    tags: ['rice', 'basmati', 'india gate'],
    price: 110.0,
    mrp: 135.0,
    rating: 4.7,
    discount: 18,
    stock: 60,
    reviewCount: 840,
    isDeal: true,
    isBestSeller: true,
    weight: '1',
    unit: 'kg',
  ),
  Product(
    id: 'gk_ard_3',
    name: 'Tata Sampann Moong Dal 500g',
    brand: 'Tata Sampann',
    category: 'grocery_kitchen',
    subcategory: 'atta_rice_dal',
    description: 'Unpolished split yellow moong dal.',
    images: ['https://images.unsplash.com/photo-1547058886-f33d9a61d196?w=500&auto=format&fit=crop&q=60'],
    tags: ['dal', 'moong', 'tata', 'pulses'],
    price: 85.0,
    mrp: 95.0,
    rating: 4.6,
    discount: 10,
    stock: 50,
    reviewCount: 420,
    isDeal: false,
    isBestSeller: false,
    weight: '500',
    unit: 'g',
  ),

  // Subcategory: Oil Ghee & Masala (oil_ghee_masala)
  Product(
    id: 'gk_ogm_1',
    name: 'Fortune Sunflower Oil 1L',
    brand: 'Fortune',
    category: 'grocery_kitchen',
    subcategory: 'oil_ghee_masala',
    description: 'Refined sunflower oil for healthy cooking.',
    images: ['https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=500&auto=format&fit=crop&q=60'],
    tags: ['oil', 'cooking oil', 'sunflower', 'fortune'],
    price: 145.0,
    mrp: 160.0,
    rating: 4.6,
    discount: 9,
    stock: 90,
    reviewCount: 1540,
    isDeal: false,
    isBestSeller: true,
    weight: '1',
    unit: 'L',
  ),
  Product(
    id: 'gk_ogm_2',
    name: 'Amul Pure Ghee 500g',
    brand: 'Amul',
    category: 'grocery_kitchen',
    subcategory: 'oil_ghee_masala',
    description: 'Pure clarified cow butter.',
    images: ['https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=500&auto=format&fit=crop&q=60'],
    tags: ['ghee', 'amul', 'clarified butter'],
    price: 340.0,
    mrp: 360.0,
    rating: 4.8,
    discount: 5,
    stock: 40,
    reviewCount: 1204,
    isDeal: false,
    isBestSeller: true,
    weight: '500',
    unit: 'g',
  ),

  // Subcategory: Dairy Bread & Eggs (dairy_bread)
  Product(
    id: 'gk_dbe_1',
    name: 'Amul Taaza Milk 1L',
    brand: 'Amul',
    category: 'grocery_kitchen',
    subcategory: 'dairy_bread',
    description: 'Fresh toned milk tetrapack.',
    images: ['https://images.unsplash.com/photo-1563636619-e9143da7973b?w=500&auto=format&fit=crop&q=60'],
    tags: ['milk', 'toned milk', 'amul'],
    price: 54.0,
    mrp: 56.0,
    rating: 4.8,
    discount: 3,
    stock: 120,
    reviewCount: 4500,
    isDeal: false,
    isBestSeller: true,
    weight: '1',
    unit: 'L',
  ),
  Product(
    id: 'gk_dbe_2',
    name: 'Britannia Whole Wheat Bread',
    brand: 'Britannia',
    category: 'grocery_kitchen',
    subcategory: 'dairy_bread',
    description: 'Healthy and soft whole wheat bread slice.',
    images: ['https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500&auto=format&fit=crop&q=60'],
    tags: ['bread', 'wheat bread', 'britannia'],
    price: 45.0,
    mrp: 50.0,
    rating: 4.7,
    discount: 10,
    stock: 35,
    reviewCount: 1230,
    isDeal: true,
    isBestSeller: true,
    weight: '400',
    unit: 'g',
  ),

  // PART 2 — SNACKS & DRINKS PRODUCTS
  // Subcategory: Chips & Namkeen (chips_namkeen)
  Product(
    id: 'sd_cn_1',
    name: 'Lays Cream & Onion 73g',
    brand: 'Lays',
    category: 'snacks_drinks',
    subcategory: 'chips_namkeen',
    description: 'American style potato chips.',
    images: ['https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=500&auto=format&fit=crop&q=60'],
    tags: ['lays', 'chips', 'snacks', 'potato chips'],
    price: 30.0,
    mrp: 30.0,
    rating: 4.7,
    discount: 0,
    stock: 150,
    reviewCount: 2890,
    isDeal: false,
    isBestSeller: true,
    weight: '73',
    unit: 'g',
  ),
  Product(
    id: 'sd_cn_2',
    name: 'Kurkure Masala Munch 90g',
    brand: 'Kurkure',
    category: 'snacks_drinks',
    subcategory: 'chips_namkeen',
    description: 'Spicy and crunchy corn puffs.',
    images: ['https://images.unsplash.com/photo-1599490659223-e153cb53d5d6?w=500&auto=format&fit=crop&q=60'],
    tags: ['kurkure', 'masala munch', 'namkeen', 'snacks'],
    price: 20.0,
    mrp: 20.0,
    rating: 4.6,
    discount: 0,
    stock: 200,
    reviewCount: 3105,
    isDeal: false,
    isBestSeller: true,
    weight: '90',
    unit: 'g',
  ),

  // Subcategory: Sweets & Chocolates (sweets_chocolates)
  Product(
    id: 'sd_sc_1',
    name: 'Cadbury Silk 150g',
    brand: 'Cadbury',
    category: 'snacks_drinks',
    subcategory: 'sweets_chocolates',
    description: 'Rich and creamy milk chocolate.',
    images: ['https://images.unsplash.com/photo-1549007994-cb92ca71450a?w=500&auto=format&fit=crop&q=60'],
    tags: ['chocolate', 'cadbury', 'silk', 'sweet'],
    price: 165.0,
    mrp: 175.0,
    rating: 4.9,
    discount: 5,
    stock: 80,
    reviewCount: 4230,
    isDeal: false,
    isBestSeller: true,
    weight: '150',
    unit: 'g',
  ),

  // Subcategory: Drinks & Juices (drinks_juices)
  Product(
    id: 'sd_dj_1',
    name: 'Tropicana Orange Juice 1L',
    brand: 'Tropicana',
    category: 'snacks_drinks',
    subcategory: 'drinks_juices',
    description: '100% pure orange juice.',
    images: ['https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?w=500&auto=format&fit=crop&q=60'],
    tags: ['juice', 'orange', 'tropicana', 'beverage'],
    price: 110.0,
    mrp: 130.0,
    rating: 4.6,
    discount: 15,
    stock: 45,
    reviewCount: 780,
    isDeal: true,
    isBestSeller: false,
    weight: '1',
    unit: 'L',
  ),

  // PART 3 — BEAUTY & PERSONAL CARE PRODUCTS
  // Subcategory: Skin & Face (skin_face)
  Product(
    id: 'bp_sf_1',
    name: 'Nivea Soft Cream 200ml',
    brand: 'Nivea',
    category: 'beauty_care',
    subcategory: 'skin_face',
    description: 'Light moisturising cream.',
    images: ['https://images.unsplash.com/photo-1556228720-195a672e8a03?w=500&auto=format&fit=crop&q=60'],
    tags: ['nivea', 'moisturiser', 'skin cream'],
    price: 270.0,
    mrp: 299.0,
    rating: 4.8,
    discount: 10,
    stock: 50,
    reviewCount: 1430,
    isDeal: false,
    isBestSeller: true,
    weight: '200',
    unit: 'ml',
  ),

  // PART 4 — HOUSEHOLD PRODUCTS
  // Subcategory: Detergents (detergents)
  Product(
    id: 'hh_dt_1',
    name: 'Ariel Matic Liquid 1L',
    brand: 'Ariel',
    category: 'household',
    subcategory: 'detergents',
    description: 'Front load liquid detergent.',
    images: ['https://images.unsplash.com/photo-1584824486509-112e4181ff6b?w=500&auto=format&fit=crop&q=60'],
    tags: ['detergent', 'liquid', 'ariel', 'washing'],
    price: 220.0,
    mrp: 250.0,
    rating: 4.7,
    discount: 12,
    stock: 35,
    reviewCount: 920,
    isDeal: false,
    isBestSeller: true,
    weight: '1',
    unit: 'L',
  ),

  // PART 5 — PHARMACY PRODUCTS
  // Subcategory: Medicines (medicines)
  Product(
    id: 'ph_md_1',
    name: 'Crocin Pain Relief 500mg',
    brand: 'Crocin',
    category: 'pharmacy',
    subcategory: 'medicines',
    description: 'Fever and pain relief tablets.',
    images: ['https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=60'],
    tags: ['crocin', 'pain relief', 'fever', 'tablet'],
    price: 22.0,
    mrp: 22.0,
    rating: 4.9,
    discount: 0,
    stock: 200,
    reviewCount: 1890,
    isDeal: false,
    isBestSeller: false,
    weight: '15',
    unit: 'tablets',
  ),

  // PART 6 — DAIRY & BREAD
  Product(
    id: 'db_1',
    name: 'Amul Masti Dahi 400g',
    brand: 'Amul',
    category: 'dairy_bread',
    subcategory: 'Curd & Yoghurt',
    description: 'Creamy and fresh curd cup.',
    images: ['https://images.unsplash.com/photo-1488477181946-6428a0291777?w=500&auto=format&fit=crop&q=60'],
    tags: ['dahi', 'curd', 'amul'],
    price: 35.0,
    mrp: 35.0,
    rating: 4.8,
    discount: 0,
    stock: 75,
    reviewCount: 1605,
    isDeal: false,
    isBestSeller: true,
    weight: '400',
    unit: 'g',
  ),

  // PART 7 — FRUITS & VEGETABLES
  Product(
    id: 'fv_1',
    name: 'Fresh Red Tomatoes 500g',
    brand: 'Fresh Farm',
    category: 'fruits_veg',
    subcategory: 'Vegetables',
    description: 'Fresh organic red tomatoes.',
    images: ['https://images.unsplash.com/photo-1595855759920-86582396756a?w=500&auto=format&fit=crop&q=60'],
    tags: ['tomato', 'veg', 'fresh'],
    price: 45.0,
    mrp: 60.0,
    rating: 4.8,
    discount: 25,
    stock: 90,
    reviewCount: 4302,
    isDeal: true,
    isBestSeller: true,
    weight: '500',
    unit: 'g',
  ),

  // PART 8 — BABY CARE
  Product(
    id: 'bc_1',
    name: 'Pampers Premium Care Diapers M',
    brand: 'Pampers',
    category: 'baby_care',
    subcategory: 'diapers',
    description: 'Premium diapers for babies.',
    images: ['https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=500&auto=format&fit=crop&q=60'],
    tags: ['diaper', 'baby', 'pampers'],
    price: 749.0,
    mrp: 899.0,
    rating: 4.8,
    discount: 16,
    stock: 25,
    reviewCount: 450,
    isDeal: true,
    isBestSeller: true,
    weight: '58',
    unit: 'pcs',
  ),

  // PART 9 — ELECTRONICS
  Product(
    id: 'el_1',
    name: 'boAt Rockerz 450 Headphone',
    brand: 'boAt',
    category: 'electronics',
    subcategory: 'audio',
    description: 'Wireless Bluetooth headphones.',
    images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&auto=format&fit=crop&q=60'],
    tags: ['headphone', 'boat', 'audio', 'bluetooth'],
    price: 1499.0,
    mrp: 2999.0,
    rating: 4.5,
    discount: 50,
    stock: 12,
    reviewCount: 1540,
    isDeal: true,
    isBestSeller: true,
    weight: '1',
    unit: 'unit',
  ),

  // PART 10 — TOYS & GAMES
  Product(
    id: 'tg_1',
    name: 'LEGO Classic Creative Bricks',
    brand: 'LEGO',
    category: 'toys_games',
    subcategory: 'toys',
    description: 'LEGO bricks creative set.',
    images: ['https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=500&auto=format&fit=crop&q=60'],
    tags: ['lego', 'bricks', 'toys', 'creative'],
    price: 1299.0,
    mrp: 1499.0,
    rating: 4.9,
    discount: 13,
    stock: 10,
    reviewCount: 650,
    isDeal: false,
    isBestSeller: true,
    weight: '484',
    unit: 'pcs',
  ),

  // PART 11 — SPORTS
  Product(
    id: 'sp_1',
    name: 'Cosco Football Size 5',
    brand: 'Cosco',
    category: 'sports',
    subcategory: 'balls',
    description: 'Professional training football.',
    images: ['https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=500&auto=format&fit=crop&q=60'],
    tags: ['football', 'cosco', 'soccer', 'sports'],
    price: 499.0,
    mrp: 599.0,
    rating: 4.6,
    discount: 16,
    stock: 15,
    reviewCount: 320,
    isDeal: false,
    isBestSeller: true,
    weight: '1',
    unit: 'unit',
  ),

  // PART 12 — GIFTING
  Product(
    id: 'gf_1',
    name: 'Cadbury Celebration Gift Box',
    brand: 'Cadbury',
    category: 'gifting',
    subcategory: 'chocolates',
    description: 'Assorted chocolate gift box.',
    images: ['https://images.unsplash.com/photo-1549007994-cb92ca71450a?w=500&auto=format&fit=crop&q=60'],
    tags: ['gift', 'cadbury', 'chocolate'],
    price: 140.0,
    mrp: 150.0,
    rating: 4.8,
    discount: 6,
    stock: 60,
    reviewCount: 2100,
    isDeal: true,
    isBestSeller: true,
    weight: '281',
    unit: 'g',
  ),
  Product(
    id: 'gf_2',
    name: 'Ferrero Rocher Box 16pcs',
    brand: 'Ferrero',
    category: 'gifting',
    subcategory: 'chocolates',
    description: 'Premium hazelnut chocolate gift box.',
    images: ['https://images.unsplash.com/photo-1481391319762-47dff72954d9?w=500&auto=format&fit=crop&q=60'],
    tags: ['gift', 'ferrero', 'chocolate', 'premium'],
    price: 549.0,
    mrp: 699.0,
    rating: 4.9,
    discount: 21,
    stock: 40,
    reviewCount: 1800,
    isDeal: true,
    isBestSeller: true,
    weight: '200',
    unit: 'g',
  ),
  Product(
    id: 'gf_3',
    name: 'Rose Bouquet (12 Fresh Stems)',
    brand: 'FNP',
    category: 'gifting',
    subcategory: 'flowers',
    description: 'Fresh red roses, delivered same day.',
    images: ['https://images.unsplash.com/photo-1490750967868-88df5691cc5b?w=500&auto=format&fit=crop&q=60'],
    tags: ['gift', 'flowers', 'roses', 'fresh'],
    price: 699.0,
    mrp: 999.0,
    rating: 4.7,
    discount: 30,
    stock: 20,
    reviewCount: 960,
    isDeal: true,
    isBestSeller: false,
    weight: '12',
    unit: 'stems',
  ),
  Product(
    id: 'gf_4',
    name: 'Premium Gift Hamper Box',
    brand: 'Ferns N Petals',
    category: 'gifting',
    subcategory: 'hampers',
    description: 'Curated gift hamper with chocolates, dry fruits & more.',
    images: ['https://images.unsplash.com/photo-1607344645866-009c320b63e0?w=500&auto=format&fit=crop&q=60'],
    tags: ['gift', 'hamper', 'premium', 'occasion'],
    price: 1499.0,
    mrp: 2199.0,
    rating: 4.8,
    discount: 31,
    stock: 15,
    reviewCount: 540,
    isDeal: true,
    isBestSeller: true,
    weight: '1',
    unit: 'set',
  ),
  Product(
    id: 'gf_5',
    name: 'Personalized Mug',
    brand: 'PrintStop',
    category: 'gifting',
    subcategory: 'personalized',
    description: 'Custom printed ceramic mug.',
    images: ['https://images.unsplash.com/photo-1504972078668-bb7e40f2a5d3?w=500&auto=format&fit=crop&q=60'],
    tags: ['gift', 'mug', 'personalized', 'custom'],
    price: 349.0,
    mrp: 499.0,
    rating: 4.6,
    discount: 30,
    stock: 30,
    reviewCount: 720,
    isDeal: false,
    isBestSeller: false,
    weight: '1',
    unit: 'pc',
  ),
  Product(
    id: 'gf_6',
    name: 'Silk Gift Wrap Set',
    brand: 'Hallmark',
    category: 'gifting',
    subcategory: 'wrapping',
    description: 'Luxury gift wrapping set with ribbons and tags.',
    images: ['https://images.unsplash.com/photo-1512909006721-3d6018887383?w=500&auto=format&fit=crop&q=60'],
    tags: ['gift', 'wrap', 'ribbon', 'hallmark'],
    price: 199.0,
    mrp: 299.0,
    rating: 4.4,
    discount: 33,
    stock: 50,
    reviewCount: 350,
    isDeal: false,
    isBestSeller: false,
    weight: '5',
    unit: 'pcs',
  ),

  // BEAUTY & CARE
  Product(
    id: 'bc_2',
    name: 'Lakme Rose Face Powder',
    brand: 'Lakme',
    category: 'beauty_care',
    subcategory: 'makeup',
    description: 'Smooth translucent face powder.',
    images: ['https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=500&auto=format&fit=crop&q=60'],
    tags: ['makeup', 'powder', 'lakme', 'face'],
    price: 149.0,
    mrp: 199.0,
    rating: 4.5,
    discount: 25,
    stock: 80,
    reviewCount: 1200,
    isDeal: false,
    isBestSeller: true,
    weight: '40',
    unit: 'g',
  ),
  Product(
    id: 'bc_3',
    name: 'Maybelline Fit Me Foundation',
    brand: 'Maybelline',
    category: 'beauty_care',
    subcategory: 'makeup',
    description: 'Natural finish liquid foundation.',
    images: ['https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=500&auto=format&fit=crop&q=60'],
    tags: ['makeup', 'foundation', 'maybelline', 'face'],
    price: 349.0,
    mrp: 499.0,
    rating: 4.7,
    discount: 30,
    stock: 60,
    reviewCount: 2400,
    isDeal: true,
    isBestSeller: true,
    weight: '30',
    unit: 'ml',
  ),
  Product(
    id: 'bc_4',
    name: 'Neutrogena Deep Moisture Cream',
    brand: 'Neutrogena',
    category: 'beauty_care',
    subcategory: 'skincare',
    description: 'Deep moisture body lotion.',
    images: ['https://images.unsplash.com/photo-1556228841-a3c527ebefe5?w=500&auto=format&fit=crop&q=60'],
    tags: ['skincare', 'moisturizer', 'neutrogena', 'lotion'],
    price: 399.0,
    mrp: 599.0,
    rating: 4.6,
    discount: 33,
    stock: 45,
    reviewCount: 980,
    isDeal: true,
    isBestSeller: false,
    weight: '50',
    unit: 'ml',
  ),
  Product(
    id: 'bc_5',
    name: "L'Oreal Paris Lipstick",
    brand: "L'Oreal",
    category: 'beauty_care',
    subcategory: 'makeup',
    description: 'Long-lasting matte lipstick.',
    images: ['https://images.unsplash.com/photo-1586495777744-4e6232bf2b77?w=500&auto=format&fit=crop&q=60'],
    tags: ['lipstick', 'loreal', 'makeup', 'matte'],
    price: 449.0,
    mrp: 699.0,
    rating: 4.8,
    discount: 35,
    stock: 55,
    reviewCount: 3100,
    isDeal: true,
    isBestSeller: true,
    weight: '3',
    unit: 'g',
  ),
  Product(
    id: 'bc_6',
    name: 'Dove Shampoo 650ml',
    brand: 'Dove',
    category: 'beauty_care',
    subcategory: 'haircare',
    description: 'Nourishing shampoo for damaged hair.',
    images: ['https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=500&auto=format&fit=crop&q=60'],
    tags: ['shampoo', 'dove', 'haircare', 'nourishing'],
    price: 279.0,
    mrp: 349.0,
    rating: 4.6,
    discount: 20,
    stock: 90,
    reviewCount: 1850,
    isDeal: false,
    isBestSeller: true,
    weight: '650',
    unit: 'ml',
  ),
  Product(
    id: 'bc_7',
    name: 'The Body Shop Tea Tree Oil',
    brand: 'The Body Shop',
    category: 'beauty_care',
    subcategory: 'skincare',
    description: 'Pure tea tree essential oil for skin.',
    images: ['https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=500&auto=format&fit=crop&q=60'],
    tags: ['skincare', 'tea tree', 'body shop', 'oil'],
    price: 799.0,
    mrp: 1099.0,
    rating: 4.7,
    discount: 27,
    stock: 35,
    reviewCount: 670,
    isDeal: true,
    isBestSeller: false,
    weight: '30',
    unit: 'ml',
  ),

  // HOUSEHOLD
  Product(
    id: 'hh_2',
    name: 'Vim Dishwash Liquid 750ml',
    brand: 'Vim',
    category: 'household',
    subcategory: 'cleaners',
    description: 'Grease-cutting dishwash liquid.',
    images: ['https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=500&auto=format&fit=crop&q=60'],
    tags: ['vim', 'dishwash', 'cleaner', 'kitchen'],
    price: 89.0,
    mrp: 115.0,
    rating: 4.6,
    discount: 22,
    stock: 200,
    reviewCount: 3400,
    isDeal: false,
    isBestSeller: true,
    weight: '750',
    unit: 'ml',
  ),
  Product(
    id: 'hh_3',
    name: 'Lizol Floor Cleaner 1L',
    brand: 'Lizol',
    category: 'household',
    subcategory: 'cleaners',
    description: 'Disinfectant floor cleaner.',
    images: ['https://images.unsplash.com/photo-1600435335786-d74d2bb6be87?w=500&auto=format&fit=crop&q=60'],
    tags: ['floor cleaner', 'lizol', 'disinfectant', 'household'],
    price: 149.0,
    mrp: 189.0,
    rating: 4.7,
    discount: 21,
    stock: 150,
    reviewCount: 2100,
    isDeal: true,
    isBestSeller: true,
    weight: '1',
    unit: 'L',
  ),
  Product(
    id: 'hh_4',
    name: 'Harpic Power Plus 500ml',
    brand: 'Harpic',
    category: 'household',
    subcategory: 'cleaners',
    description: '10X toilet cleaning power.',
    images: ['https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=500&auto=format&fit=crop&q=60'],
    tags: ['harpic', 'toilet cleaner', 'household', 'bathroom'],
    price: 105.0,
    mrp: 130.0,
    rating: 4.5,
    discount: 19,
    stock: 120,
    reviewCount: 1600,
    isDeal: false,
    isBestSeller: true,
    weight: '500',
    unit: 'ml',
  ),
  Product(
    id: 'hh_5',
    name: 'Ariel Matic Powder 2kg',
    brand: 'Ariel',
    category: 'household',
    subcategory: 'laundry',
    description: 'Front load washing machine detergent.',
    images: ['https://images.unsplash.com/photo-1604335399105-a0c585fd81a1?w=500&auto=format&fit=crop&q=60'],
    tags: ['ariel', 'detergent', 'laundry', 'washing'],
    price: 399.0,
    mrp: 520.0,
    rating: 4.8,
    discount: 23,
    stock: 80,
    reviewCount: 4200,
    isDeal: true,
    isBestSeller: true,
    weight: '2',
    unit: 'kg',
  ),
  Product(
    id: 'hh_6',
    name: 'Febreze Air Freshener 300ml',
    brand: 'Febreze',
    category: 'household',
    subcategory: 'fresheners',
    description: 'Eliminates odours, fresh linen scent.',
    images: ['https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=500&auto=format&fit=crop&q=60'],
    tags: ['air freshener', 'febreze', 'odour', 'household'],
    price: 299.0,
    mrp: 379.0,
    rating: 4.4,
    discount: 21,
    stock: 60,
    reviewCount: 890,
    isDeal: false,
    isBestSeller: false,
    weight: '300',
    unit: 'ml',
  ),

  // PHARMACY
  Product(
    id: 'ph_2',
    name: 'Crocin 500mg Tablets',
    brand: 'GSK',
    category: 'pharmacy',
    subcategory: 'medicines',
    description: 'Paracetamol tablets for fever & pain.',
    images: ['https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=60'],
    tags: ['crocin', 'paracetamol', 'fever', 'medicine'],
    price: 29.0,
    mrp: 36.0,
    rating: 4.8,
    discount: 19,
    stock: 500,
    reviewCount: 5600,
    isDeal: false,
    isBestSeller: true,
    weight: '15',
    unit: 'tabs',
  ),
  Product(
    id: 'ph_3',
    name: 'Himalaya Vitamin C Tablets',
    brand: 'Himalaya',
    category: 'pharmacy',
    subcategory: 'supplements',
    description: 'Immunity boosting Vitamin C.',
    images: ['https://images.unsplash.com/photo-1550572017-edd951b55104?w=500&auto=format&fit=crop&q=60'],
    tags: ['vitamin c', 'himalaya', 'supplement', 'immunity'],
    price: 199.0,
    mrp: 260.0,
    rating: 4.7,
    discount: 23,
    stock: 180,
    reviewCount: 2200,
    isDeal: true,
    isBestSeller: true,
    weight: '60',
    unit: 'tabs',
  ),
  Product(
    id: 'ph_4',
    name: 'Band-Aid Flexible Strips',
    brand: 'Band-Aid',
    category: 'pharmacy',
    subcategory: 'firstaid',
    description: '30 assorted bandages for cuts.',
    images: ['https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?w=500&auto=format&fit=crop&q=60'],
    tags: ['bandage', 'band-aid', 'first aid', 'wound'],
    price: 79.0,
    mrp: 99.0,
    rating: 4.6,
    discount: 20,
    stock: 300,
    reviewCount: 1800,
    isDeal: false,
    isBestSeller: true,
    weight: '30',
    unit: 'pcs',
  ),
  Product(
    id: 'ph_5',
    name: 'Dettol Antiseptic Liquid 100ml',
    brand: 'Dettol',
    category: 'pharmacy',
    subcategory: 'firstaid',
    description: 'Antiseptic liquid for wound care.',
    images: ['https://images.unsplash.com/photo-1584820927498-cfe5211fd8bf?w=500&auto=format&fit=crop&q=60'],
    tags: ['dettol', 'antiseptic', 'first aid', 'wound care'],
    price: 89.0,
    mrp: 119.0,
    rating: 4.8,
    discount: 25,
    stock: 250,
    reviewCount: 3400,
    isDeal: false,
    isBestSeller: true,
    weight: '100',
    unit: 'ml',
  ),
  Product(
    id: 'ph_6',
    name: 'Livogen Tonic 100ml',
    brand: 'Livogen',
    category: 'pharmacy',
    subcategory: 'supplements',
    description: 'Iron & folic acid tonic for anaemia.',
    images: ['https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=500&auto=format&fit=crop&q=60'],
    tags: ['livogen', 'iron', 'tonic', 'supplement'],
    price: 149.0,
    mrp: 195.0,
    rating: 4.5,
    discount: 23,
    stock: 90,
    reviewCount: 1100,
    isDeal: false,
    isBestSeller: false,
    weight: '100',
    unit: 'ml',
  ),

  // BABY CARE
  Product(
    id: 'baby_2',
    name: 'Johnson Baby Lotion 200ml',
    brand: "Johnson's",
    category: 'baby_care',
    subcategory: 'skincare',
    description: 'Gentle moisturizing lotion for babies.',
    images: ['https://images.unsplash.com/photo-1515488042361-404e9250afef?w=500&auto=format&fit=crop&q=60'],
    tags: ['baby', 'lotion', 'johnson', 'skincare'],
    price: 149.0,
    mrp: 189.0,
    rating: 4.8,
    discount: 21,
    stock: 200,
    reviewCount: 4500,
    isDeal: false,
    isBestSeller: true,
    weight: '200',
    unit: 'ml',
  ),
  Product(
    id: 'baby_3',
    name: 'Cerelac Wheat Stage 1 300g',
    brand: 'Nestle',
    category: 'baby_care',
    subcategory: 'food',
    description: 'Nutritious wheat cereal for 6+ months.',
    images: ['https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=500&auto=format&fit=crop&q=60'],
    tags: ['cerelac', 'baby food', 'nestle', 'cereal'],
    price: 215.0,
    mrp: 255.0,
    rating: 4.9,
    discount: 15,
    stock: 150,
    reviewCount: 3200,
    isDeal: true,
    isBestSeller: true,
    weight: '300',
    unit: 'g',
  ),
  Product(
    id: 'baby_4',
    name: 'Mee Mee Feeding Bottle 250ml',
    brand: 'Mee Mee',
    category: 'baby_care',
    subcategory: 'feeding',
    description: 'BPA-free feeding bottle with anti-colic nipple.',
    images: ['https://images.unsplash.com/photo-1561864174-5a52e33e30da?w=500&auto=format&fit=crop&q=60'],
    tags: ['feeding bottle', 'mee mee', 'baby', 'bpa free'],
    price: 349.0,
    mrp: 450.0,
    rating: 4.7,
    discount: 22,
    stock: 80,
    reviewCount: 2100,
    isDeal: false,
    isBestSeller: true,
    weight: '1',
    unit: 'pc',
  ),
  Product(
    id: 'baby_5',
    name: 'Himalaya Baby Shampoo 200ml',
    brand: 'Himalaya',
    category: 'baby_care',
    subcategory: 'haircare',
    description: 'Gentle no-tears baby shampoo.',
    images: ['https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=500&auto=format&fit=crop&q=60'],
    tags: ['baby shampoo', 'himalaya', 'baby', 'haircare'],
    price: 119.0,
    mrp: 150.0,
    rating: 4.8,
    discount: 20,
    stock: 160,
    reviewCount: 3800,
    isDeal: false,
    isBestSeller: true,
    weight: '200',
    unit: 'ml',
  ),
  Product(
    id: 'baby_6',
    name: 'Soft Baby Blanket',
    brand: 'Mothercare',
    category: 'baby_care',
    subcategory: 'accessories',
    description: 'Super soft cotton blanket for newborns.',
    images: ['https://images.unsplash.com/photo-1555252333-9f8e92e65df9?w=500&auto=format&fit=crop&q=60'],
    tags: ['baby blanket', 'mothercare', 'newborn', 'cotton'],
    price: 499.0,
    mrp: 699.0,
    rating: 4.7,
    discount: 28,
    stock: 60,
    reviewCount: 1400,
    isDeal: false,
    isBestSeller: false,
    weight: '1',
    unit: 'pc',
  ),

  // ELECTRONICS
  Product(
    id: 'el_2',
    name: 'Samsung 65W Type-C Charger',
    brand: 'Samsung',
    category: 'electronics',
    subcategory: 'chargers',
    description: 'Super-fast GaN charger with USB-C.',
    images: ['https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=500&auto=format&fit=crop&q=60'],
    tags: ['charger', 'samsung', 'usb-c', 'fast charge'],
    price: 1499.0,
    mrp: 1999.0,
    rating: 4.6,
    discount: 25,
    stock: 50,
    reviewCount: 1200,
    isDeal: true,
    isBestSeller: true,
    weight: '1',
    unit: 'pc',
  ),
  Product(
    id: 'el_3',
    name: 'Noise ColorFit Pro Smartwatch',
    brand: 'Noise',
    category: 'electronics',
    subcategory: 'wearables',
    description: 'Smart fitness tracker with heart rate monitor.',
    images: ['https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&auto=format&fit=crop&q=60'],
    tags: ['smartwatch', 'noise', 'fitness', 'wearable'],
    price: 2499.0,
    mrp: 4999.0,
    rating: 4.4,
    discount: 50,
    stock: 30,
    reviewCount: 8700,
    isDeal: true,
    isBestSeller: true,
    weight: '1',
    unit: 'pc',
  ),
  Product(
    id: 'el_4',
    name: 'Anker 20000mAh Power Bank',
    brand: 'Anker',
    category: 'electronics',
    subcategory: 'powerbank',
    description: 'Dual USB + USB-C power bank.',
    images: ['https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=500&auto=format&fit=crop&q=60'],
    tags: ['power bank', 'anker', 'charging', 'portable'],
    price: 1799.0,
    mrp: 2799.0,
    rating: 4.7,
    discount: 35,
    stock: 40,
    reviewCount: 5600,
    isDeal: true,
    isBestSeller: true,
    weight: '1',
    unit: 'pc',
  ),
  Product(
    id: 'el_5',
    name: 'boAt Airdopes 141 TWS Earbuds',
    brand: 'boAt',
    category: 'electronics',
    subcategory: 'audio',
    description: 'True wireless earbuds with 42hr playtime.',
    images: ['https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=500&auto=format&fit=crop&q=60'],
    tags: ['earbuds', 'boat', 'tws', 'bluetooth', 'wireless'],
    price: 1299.0,
    mrp: 2499.0,
    rating: 4.5,
    discount: 48,
    stock: 60,
    reviewCount: 12000,
    isDeal: true,
    isBestSeller: true,
    weight: '1',
    unit: 'pc',
  ),
  Product(
    id: 'el_6',
    name: 'Zebronics 2m HDMI Cable',
    brand: 'Zebronics',
    category: 'electronics',
    subcategory: 'cables',
    description: '4K HDMI 2.0 cable for TVs & monitors.',
    images: ['https://images.unsplash.com/photo-1583394838336-acd977736f90?w=500&auto=format&fit=crop&q=60'],
    tags: ['hdmi', 'cable', 'zebronics', '4k'],
    price: 299.0,
    mrp: 499.0,
    rating: 4.3,
    discount: 40,
    stock: 120,
    reviewCount: 980,
    isDeal: false,
    isBestSeller: false,
    weight: '2',
    unit: 'm',
  ),

  // STATIONERY
  Product(
    id: 'st_1',
    name: 'Reynolds 045 Ball Pen (10 Pack)',
    brand: 'Reynolds',
    category: 'stationery',
    subcategory: 'pens',
    description: 'Smooth writing ballpoint pens.',
    images: ['https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=500&auto=format&fit=crop&q=60'],
    tags: ['pen', 'reynolds', 'ballpoint', 'stationery'],
    price: 89.0,
    mrp: 119.0,
    rating: 4.6,
    discount: 25,
    stock: 500,
    reviewCount: 8900,
    isDeal: false,
    isBestSeller: true,
    weight: '10',
    unit: 'pcs',
  ),
  Product(
    id: 'st_2',
    name: 'Classmate Spiral Notebook A5',
    brand: 'Classmate',
    category: 'stationery',
    subcategory: 'notebooks',
    description: '200-page ruled spiral notebook.',
    images: ['https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=500&auto=format&fit=crop&q=60'],
    tags: ['notebook', 'classmate', 'spiral', 'stationery'],
    price: 79.0,
    mrp: 99.0,
    rating: 4.7,
    discount: 20,
    stock: 300,
    reviewCount: 4500,
    isDeal: false,
    isBestSeller: true,
    weight: '200',
    unit: 'pages',
  ),
  Product(
    id: 'st_3',
    name: 'Faber-Castell Colour Pencils 24',
    brand: 'Faber-Castell',
    category: 'stationery',
    subcategory: 'art',
    description: '24 vibrant colour pencils set.',
    images: ['https://images.unsplash.com/photo-1513542621334-a254cf47733d?w=500&auto=format&fit=crop&q=60'],
    tags: ['colour pencils', 'faber castell', 'art', 'stationery'],
    price: 199.0,
    mrp: 275.0,
    rating: 4.8,
    discount: 27,
    stock: 200,
    reviewCount: 3200,
    isDeal: true,
    isBestSeller: true,
    weight: '24',
    unit: 'pcs',
  ),
  Product(
    id: 'st_4',
    name: 'Scotch Magic Tape 12mm x 25m',
    brand: '3M Scotch',
    category: 'stationery',
    subcategory: 'adhesives',
    description: 'Invisible matte finish tape.',
    images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500&auto=format&fit=crop&q=60'],
    tags: ['tape', 'scotch', '3m', 'stationery'],
    price: 99.0,
    mrp: 130.0,
    rating: 4.5,
    discount: 23,
    stock: 400,
    reviewCount: 1800,
    isDeal: false,
    isBestSeller: true,
    weight: '25',
    unit: 'm',
  ),
  Product(
    id: 'st_5',
    name: 'Camlin Geometry Box',
    brand: 'Camlin',
    category: 'stationery',
    subcategory: 'math',
    description: 'Complete geometry set with compass.',
    images: ['https://images.unsplash.com/photo-1596568375432-c69e1afc4af7?w=500&auto=format&fit=crop&q=60'],
    tags: ['geometry box', 'camlin', 'compass', 'stationery'],
    price: 129.0,
    mrp: 175.0,
    rating: 4.6,
    discount: 26,
    stock: 160,
    reviewCount: 2400,
    isDeal: false,
    isBestSeller: true,
    weight: '1',
    unit: 'set',
  ),
  Product(
    id: 'st_6',
    name: 'Sticky Notes 3x3" (5 Colors)',
    brand: '3M Post-it',
    category: 'stationery',
    subcategory: 'office',
    description: 'Self-stick removable notes, 100 per pad.',
    images: ['https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=500&auto=format&fit=crop&q=60'],
    tags: ['sticky notes', 'post-it', '3m', 'office'],
    price: 149.0,
    mrp: 199.0,
    rating: 4.7,
    discount: 25,
    stock: 250,
    reviewCount: 3600,
    isDeal: false,
    isBestSeller: true,
    weight: '5',
    unit: 'pads',
  ),

  // PET CARE
  Product(
    id: 'pc_1',
    name: 'Pedigree Adult Dog Food 3kg',
    brand: 'Pedigree',
    category: 'pet_care',
    subcategory: 'dog_food',
    description: 'Complete nutrition for adult dogs.',
    images: ['https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?w=500&auto=format&fit=crop&q=60'],
    tags: ['dog food', 'pedigree', 'adult', 'pet'],
    price: 499.0,
    mrp: 650.0,
    rating: 4.7,
    discount: 23,
    stock: 80,
    reviewCount: 5600,
    isDeal: true,
    isBestSeller: true,
    weight: '3',
    unit: 'kg',
  ),
  Product(
    id: 'pc_2',
    name: 'Whiskas Cat Food Tuna 1.2kg',
    brand: 'Whiskas',
    category: 'pet_care',
    subcategory: 'cat_food',
    description: 'Complete dry food for adult cats.',
    images: ['https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=500&auto=format&fit=crop&q=60'],
    tags: ['cat food', 'whiskas', 'tuna', 'pet'],
    price: 399.0,
    mrp: 530.0,
    rating: 4.6,
    discount: 24,
    stock: 60,
    reviewCount: 3200,
    isDeal: false,
    isBestSeller: true,
    weight: '1.2',
    unit: 'kg',
  ),
  Product(
    id: 'pc_3',
    name: 'Pet Dog Collar with Leash',
    brand: 'PetStar',
    category: 'pet_care',
    subcategory: 'accessories',
    description: 'Adjustable nylon collar and leash set.',
    images: ['https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=500&auto=format&fit=crop&q=60'],
    tags: ['dog collar', 'leash', 'pet', 'accessories'],
    price: 299.0,
    mrp: 450.0,
    rating: 4.4,
    discount: 33,
    stock: 70,
    reviewCount: 1400,
    isDeal: false,
    isBestSeller: false,
    weight: '1',
    unit: 'set',
  ),
  Product(
    id: 'pc_4',
    name: 'Drools Puppy Dog Food 3kg',
    brand: 'Drools',
    category: 'pet_care',
    subcategory: 'dog_food',
    description: 'High protein food for puppies.',
    images: ['https://images.unsplash.com/photo-1601758125946-6ec2ef64daf8?w=500&auto=format&fit=crop&q=60'],
    tags: ['puppy food', 'drools', 'dog', 'pet'],
    price: 449.0,
    mrp: 599.0,
    rating: 4.8,
    discount: 25,
    stock: 55,
    reviewCount: 2800,
    isDeal: true,
    isBestSeller: true,
    weight: '3',
    unit: 'kg',
  ),
  Product(
    id: 'pc_5',
    name: 'Sheba Cat Wet Food 12 Pouches',
    brand: 'Sheba',
    category: 'pet_care',
    subcategory: 'cat_food',
    description: 'Premium wet food pouches for cats.',
    images: ['https://images.unsplash.com/photo-1573865526739-10659fec78a5?w=500&auto=format&fit=crop&q=60'],
    tags: ['cat food', 'sheba', 'wet food', 'pet'],
    price: 599.0,
    mrp: 780.0,
    rating: 4.7,
    discount: 23,
    stock: 45,
    reviewCount: 2100,
    isDeal: false,
    isBestSeller: true,
    weight: '12',
    unit: 'pouches',
  ),
  Product(
    id: 'pc_6',
    name: 'Pet Grooming Comb Set',
    brand: 'Wahl',
    category: 'pet_care',
    subcategory: 'grooming',
    description: 'Professional grooming comb for dogs & cats.',
    images: ['https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=500&auto=format&fit=crop&q=60'],
    tags: ['grooming', 'comb', 'wahl', 'pet'],
    price: 399.0,
    mrp: 599.0,
    rating: 4.5,
    discount: 33,
    stock: 40,
    reviewCount: 980,
    isDeal: false,
    isBestSeller: false,
    weight: '1',
    unit: 'set',
  ),

  // FASHION
  Product(
    id: 'fa_1',
    name: 'Levi\'s 511 Slim Fit Jeans',
    brand: 'Levi\'s',
    category: 'fashion',
    subcategory: 'bottomwear',
    description: 'Classic slim fit denim jeans.',
    images: ['https://images.unsplash.com/photo-1542272604-787c3835535d?w=500&auto=format&fit=crop&q=60'],
    tags: ['jeans', 'levis', 'denim', 'fashion'],
    price: 2999.0,
    mrp: 4499.0,
    rating: 4.7,
    discount: 33,
    stock: 40,
    reviewCount: 4200,
    isDeal: true,
    isBestSeller: true,
    weight: '1',
    unit: 'pc',
  ),
  Product(
    id: 'fa_2',
    name: 'Nike Dri-FIT T-Shirt',
    brand: 'Nike',
    category: 'fashion',
    subcategory: 'topwear',
    description: 'Moisture-wicking sports t-shirt.',
    images: ['https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=500&auto=format&fit=crop&q=60'],
    tags: ['t-shirt', 'nike', 'dri-fit', 'sports'],
    price: 1299.0,
    mrp: 1799.0,
    rating: 4.6,
    discount: 27,
    stock: 80,
    reviewCount: 6700,
    isDeal: true,
    isBestSeller: true,
    weight: '1',
    unit: 'pc',
  ),
  Product(
    id: 'fa_3',
    name: 'Puma Running Shoes',
    brand: 'Puma',
    category: 'fashion',
    subcategory: 'footwear',
    description: 'Lightweight running shoes with cushion.',
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&auto=format&fit=crop&q=60'],
    tags: ['shoes', 'puma', 'running', 'footwear'],
    price: 2499.0,
    mrp: 3999.0,
    rating: 4.5,
    discount: 37,
    stock: 35,
    reviewCount: 3400,
    isDeal: true,
    isBestSeller: true,
    weight: '1',
    unit: 'pair',
  ),
  Product(
    id: 'fa_4',
    name: 'H&M Cotton Kurta',
    brand: 'H&M',
    category: 'fashion',
    subcategory: 'topwear',
    description: 'Relaxed cotton kurta for everyday wear.',
    images: ['https://images.unsplash.com/photo-1594938298603-c8148c4b8fc4?w=500&auto=format&fit=crop&q=60'],
    tags: ['kurta', 'hm', 'cotton', 'ethnic'],
    price: 999.0,
    mrp: 1499.0,
    rating: 4.3,
    discount: 33,
    stock: 55,
    reviewCount: 1800,
    isDeal: false,
    isBestSeller: false,
    weight: '1',
    unit: 'pc',
  ),
  Product(
    id: 'fa_5',
    name: 'Fossil Men\'s Watch',
    brand: 'Fossil',
    category: 'fashion',
    subcategory: 'accessories',
    description: 'Minimalist quartz leather strap watch.',
    images: ['https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=500&auto=format&fit=crop&q=60'],
    tags: ['watch', 'fossil', 'men', 'accessories'],
    price: 7999.0,
    mrp: 12999.0,
    rating: 4.7,
    discount: 38,
    stock: 20,
    reviewCount: 2900,
    isDeal: true,
    isBestSeller: true,
    weight: '1',
    unit: 'pc',
  ),
  Product(
    id: 'fa_6',
    name: 'Wildcraft Backpack 30L',
    brand: 'Wildcraft',
    category: 'fashion',
    subcategory: 'bags',
    description: 'Durable travel backpack with laptop sleeve.',
    images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500&auto=format&fit=crop&q=60'],
    tags: ['backpack', 'wildcraft', 'bag', 'travel'],
    price: 1299.0,
    mrp: 1999.0,
    rating: 4.6,
    discount: 35,
    stock: 45,
    reviewCount: 3100,
    isDeal: false,
    isBestSeller: true,
    weight: '1',
    unit: 'pc',
  ),

  // TOYS & GAMES
  Product(
    id: 'tg_2',
    name: 'Hot Wheels 10-Car Gift Pack',
    brand: 'Hot Wheels',
    category: 'toys_games',
    subcategory: 'cars',
    description: 'Set of 10 die-cast toy cars.',
    images: ['https://images.unsplash.com/photo-1594787318286-3d835c1d207f?w=500&auto=format&fit=crop&q=60'],
    tags: ['hot wheels', 'cars', 'toys', 'boys'],
    price: 499.0,
    mrp: 699.0,
    rating: 4.8,
    discount: 28,
    stock: 70,
    reviewCount: 5600,
    isDeal: true,
    isBestSeller: true,
    weight: '10',
    unit: 'pcs',
  ),
  Product(
    id: 'tg_3',
    name: 'Barbie Fashionista Doll',
    brand: 'Mattel',
    category: 'toys_games',
    subcategory: 'dolls',
    description: 'Barbie doll with accessories.',
    images: ['https://images.unsplash.com/photo-1515488042361-404e9250afef?w=500&auto=format&fit=crop&q=60'],
    tags: ['barbie', 'doll', 'mattel', 'girls'],
    price: 699.0,
    mrp: 999.0,
    rating: 4.6,
    discount: 30,
    stock: 55,
    reviewCount: 4200,
    isDeal: false,
    isBestSeller: true,
    weight: '1',
    unit: 'pc',
  ),
  Product(
    id: 'tg_4',
    name: 'Play-Doh 10-Color Set',
    brand: 'Play-Doh',
    category: 'toys_games',
    subcategory: 'creative',
    description: '10 cans of non-toxic modelling clay.',
    images: ['https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=500&auto=format&fit=crop&q=60'],
    tags: ['play-doh', 'clay', 'creative', 'kids'],
    price: 349.0,
    mrp: 499.0,
    rating: 4.9,
    discount: 30,
    stock: 90,
    reviewCount: 6800,
    isDeal: true,
    isBestSeller: true,
    weight: '10',
    unit: 'cans',
  ),
  Product(
    id: 'tg_5',
    name: 'Funskool Scrabble Board Game',
    brand: 'Funskool',
    category: 'toys_games',
    subcategory: 'board_games',
    description: 'Classic word building board game.',
    images: ['https://images.unsplash.com/photo-1632501641765-e568d28b0015?w=500&auto=format&fit=crop&q=60'],
    tags: ['scrabble', 'board game', 'funskool', 'word game'],
    price: 699.0,
    mrp: 999.0,
    rating: 4.8,
    discount: 30,
    stock: 40,
    reviewCount: 3900,
    isDeal: false,
    isBestSeller: true,
    weight: '1',
    unit: 'pc',
  ),
  Product(
    id: 'tg_6',
    name: 'Magnetic Drawing Slate',
    brand: 'Crayola',
    category: 'toys_games',
    subcategory: 'educational',
    description: 'Re-usable drawing slate for kids.',
    images: ['https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=500&auto=format&fit=crop&q=60'],
    tags: ['drawing slate', 'crayola', 'educational', 'kids'],
    price: 399.0,
    mrp: 599.0,
    rating: 4.7,
    discount: 33,
    stock: 65,
    reviewCount: 2800,
    isDeal: false,
    isBestSeller: true,
    weight: '1',
    unit: 'pc',
  ),

  // SPORTS
  Product(
    id: 'sp_2',
    name: 'Nivia Carbonite Basketball',
    brand: 'Nivia',
    category: 'sports',
    subcategory: 'balls',
    description: 'Size 7 rubber basketball for outdoor play.',
    images: ['https://images.unsplash.com/photo-1546519638405-a9d1e2d2e8e4?w=500&auto=format&fit=crop&q=60'],
    tags: ['basketball', 'nivia', 'sports', 'outdoor'],
    price: 699.0,
    mrp: 999.0,
    rating: 4.5,
    discount: 30,
    stock: 40,
    reviewCount: 1900,
    isDeal: false,
    isBestSeller: true,
    weight: '1',
    unit: 'pc',
  ),
  Product(
    id: 'sp_3',
    name: 'Boldfit Resistance Band Set',
    brand: 'Boldfit',
    category: 'sports',
    subcategory: 'fitness',
    description: '5 resistance bands for home workouts.',
    images: ['https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500&auto=format&fit=crop&q=60'],
    tags: ['resistance band', 'boldfit', 'fitness', 'exercise'],
    price: 299.0,
    mrp: 499.0,
    rating: 4.6,
    discount: 40,
    stock: 120,
    reviewCount: 4500,
    isDeal: true,
    isBestSeller: true,
    weight: '5',
    unit: 'pcs',
  ),
  Product(
    id: 'sp_4',
    name: 'Yonex Mavis 350 Shuttlecock (6)',
    brand: 'Yonex',
    category: 'sports',
    subcategory: 'badminton',
    description: 'Nylon shuttlecocks for medium speed.',
    images: ['https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?w=500&auto=format&fit=crop&q=60'],
    tags: ['shuttlecock', 'yonex', 'badminton', 'sports'],
    price: 349.0,
    mrp: 450.0,
    rating: 4.8,
    discount: 22,
    stock: 200,
    reviewCount: 6700,
    isDeal: false,
    isBestSeller: true,
    weight: '6',
    unit: 'pcs',
  ),
  Product(
    id: 'sp_5',
    name: 'Portzon Yoga Mat 6mm',
    brand: 'Portzon',
    category: 'sports',
    subcategory: 'yoga',
    description: 'Anti-slip exercise yoga mat with carry strap.',
    images: ['https://images.unsplash.com/photo-1601925228536-c24c89c7ab38?w=500&auto=format&fit=crop&q=60'],
    tags: ['yoga mat', 'portzon', 'yoga', 'fitness'],
    price: 599.0,
    mrp: 899.0,
    rating: 4.6,
    discount: 33,
    stock: 90,
    reviewCount: 3800,
    isDeal: true,
    isBestSeller: true,
    weight: '1',
    unit: 'pc',
  ),
  Product(
    id: 'sp_6',
    name: 'Reebok Gym Gloves',
    brand: 'Reebok',
    category: 'sports',
    subcategory: 'fitness',
    description: 'Padded workout gloves for weightlifting.',
    images: ['https://images.unsplash.com/photo-1584735175315-9d5df23be31c?w=500&auto=format&fit=crop&q=60'],
    tags: ['gym gloves', 'reebok', 'weightlifting', 'fitness'],
    price: 499.0,
    mrp: 799.0,
    rating: 4.5,
    discount: 37,
    stock: 60,
    reviewCount: 2200,
    isDeal: false,
    isBestSeller: false,
    weight: '1',
    unit: 'pair',
  ),

  // BOOKS
  Product(
    id: 'bk_1',
    name: 'Atomic Habits by James Clear',
    brand: 'Penguin',
    category: 'books',
    subcategory: 'self_help',
    description: 'Tiny changes, remarkable results.',
    images: ['https://images.unsplash.com/photo-1512820790803-83ca734da794?w=500&auto=format&fit=crop&q=60'],
    tags: ['book', 'atomic habits', 'self help', 'james clear'],
    price: 399.0,
    mrp: 599.0,
    rating: 4.9,
    discount: 33,
    stock: 150,
    reviewCount: 18000,
    isDeal: true,
    isBestSeller: true,
    weight: '1',
    unit: 'pc',
  ),
  Product(
    id: 'bk_2',
    name: 'Rich Dad Poor Dad',
    brand: 'Plata Publishing',
    category: 'books',
    subcategory: 'finance',
    description: 'Personal finance classic by Robert Kiyosaki.',
    images: ['https://images.unsplash.com/photo-1554496490-b53f60cbf1c4?w=500&auto=format&fit=crop&q=60'],
    tags: ['book', 'rich dad', 'finance', 'kiyosaki'],
    price: 299.0,
    mrp: 449.0,
    rating: 4.8,
    discount: 33,
    stock: 200,
    reviewCount: 22000,
    isDeal: true,
    isBestSeller: true,
    weight: '1',
    unit: 'pc',
  ),
  Product(
    id: 'bk_3',
    name: 'The Alchemist (Hindi)',
    brand: 'HarperCollins',
    category: 'books',
    subcategory: 'fiction',
    description: 'Paulo Coelho\'s timeless adventure story.',
    images: ['https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=500&auto=format&fit=crop&q=60'],
    tags: ['book', 'alchemist', 'paulo coelho', 'fiction'],
    price: 199.0,
    mrp: 299.0,
    rating: 4.9,
    discount: 33,
    stock: 180,
    reviewCount: 15000,
    isDeal: false,
    isBestSeller: true,
    weight: '1',
    unit: 'pc',
  ),
  Product(
    id: 'bk_4',
    name: 'Think and Grow Rich',
    brand: 'Fingerprint Publishing',
    category: 'books',
    subcategory: 'self_help',
    description: 'Napoleon Hill\'s money mindset classic.',
    images: ['https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=500&auto=format&fit=crop&q=60'],
    tags: ['book', 'think grow rich', 'napoleon hill', 'self help'],
    price: 149.0,
    mrp: 225.0,
    rating: 4.8,
    discount: 33,
    stock: 220,
    reviewCount: 12000,
    isDeal: false,
    isBestSeller: true,
    weight: '1',
    unit: 'pc',
  ),
  Product(
    id: 'bk_5',
    name: 'Wings of Fire (APJ Abdul Kalam)',
    brand: 'Universities Press',
    category: 'books',
    subcategory: 'biography',
    description: 'Autobiography of India\'s Missile Man.',
    images: ['https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=500&auto=format&fit=crop&q=60'],
    tags: ['book', 'wings of fire', 'kalam', 'biography'],
    price: 179.0,
    mrp: 250.0,
    rating: 4.9,
    discount: 28,
    stock: 300,
    reviewCount: 25000,
    isDeal: true,
    isBestSeller: true,
    weight: '1',
    unit: 'pc',
  ),
  Product(
    id: 'bk_6',
    name: 'NCERT Class 10 Science',
    brand: 'NCERT',
    category: 'books',
    subcategory: 'academic',
    description: 'Official NCERT textbook for Class 10.',
    images: ['https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=500&auto=format&fit=crop&q=60'],
    tags: ['ncert', 'science', 'class 10', 'academic'],
    price: 89.0,
    mrp: 115.0,
    rating: 4.7,
    discount: 22,
    stock: 400,
    reviewCount: 8900,
    isDeal: false,
    isBestSeller: true,
    weight: '1',
    unit: 'pc',
  ),

  // SNACKS & DRINKS (additional)
  Product(
    id: 'sd_5',
    name: 'Too Yumm! Veggie Sticks 90g',
    brand: 'Too Yumm',
    category: 'snacks_drinks',
    subcategory: 'chips',
    description: 'Baked veggie sticks, less fat.',
    images: ['https://images.unsplash.com/photo-1599490659213-e2b9527bd087?w=500&auto=format&fit=crop&q=60'],
    tags: ['snacks', 'veggie sticks', 'baked', 'healthy'],
    price: 30.0,
    mrp: 40.0,
    rating: 4.5,
    discount: 25,
    stock: 200,
    reviewCount: 3400,
    isDeal: false,
    isBestSeller: true,
    weight: '90',
    unit: 'g',
  ),
  Product(
    id: 'sd_6',
    name: 'Cadbury Bournvita 500g',
    brand: 'Cadbury',
    category: 'snacks_drinks',
    subcategory: 'health_drinks',
    description: 'Malted chocolate health drink.',
    images: ['https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=500&auto=format&fit=crop&q=60'],
    tags: ['bournvita', 'cadbury', 'health drink', 'chocolate'],
    price: 249.0,
    mrp: 310.0,
    rating: 4.8,
    discount: 19,
    stock: 150,
    reviewCount: 8900,
    isDeal: false,
    isBestSeller: true,
    weight: '500',
    unit: 'g',
  ),
  Product(
    id: 'sd_7',
    name: 'Haldiram Aloo Bhujia 200g',
    brand: 'Haldiram',
    category: 'snacks_drinks',
    subcategory: 'namkeen',
    description: 'Crispy spiced potato bhujia.',
    images: ['https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=500&auto=format&fit=crop&q=60'],
    tags: ['bhujia', 'haldiram', 'namkeen', 'snack'],
    price: 79.0,
    mrp: 99.0,
    rating: 4.7,
    discount: 20,
    stock: 300,
    reviewCount: 12000,
    isDeal: false,
    isBestSeller: true,
    weight: '200',
    unit: 'g',
  ),
  Product(
    id: 'sd_8',
    name: 'Coca-Cola 2L Bottle',
    brand: 'Coca-Cola',
    category: 'snacks_drinks',
    subcategory: 'beverages',
    description: 'Refreshing cola drink.',
    images: ['https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?w=500&auto=format&fit=crop&q=60'],
    tags: ['coca cola', 'cold drink', 'beverages', 'cola'],
    price: 90.0,
    mrp: 105.0,
    rating: 4.6,
    discount: 14,
    stock: 200,
    reviewCount: 7800,
    isDeal: false,
    isBestSeller: true,
    weight: '2',
    unit: 'L',
  ),

  // DAIRY & BREAD (additional)
  Product(
    id: 'db_4',
    name: 'Mother Dairy Paneer 200g',
    brand: 'Mother Dairy',
    category: 'dairy_bread',
    subcategory: 'paneer',
    description: 'Fresh soft cottage cheese.',
    images: ['https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=500&auto=format&fit=crop&q=60'],
    tags: ['paneer', 'mother dairy', 'dairy', 'cheese'],
    price: 79.0,
    mrp: 95.0,
    rating: 4.7,
    discount: 16,
    stock: 100,
    reviewCount: 3400,
    isDeal: false,
    isBestSeller: true,
    weight: '200',
    unit: 'g',
  ),
  Product(
    id: 'db_5',
    name: 'Epigamia Greek Yogurt 400g',
    brand: 'Epigamia',
    category: 'dairy_bread',
    subcategory: 'yogurt',
    description: 'High protein Greek style yogurt.',
    images: ['https://images.unsplash.com/photo-1488477181946-6428a0291777?w=500&auto=format&fit=crop&q=60'],
    tags: ['yogurt', 'epigamia', 'greek', 'protein'],
    price: 89.0,
    mrp: 110.0,
    rating: 4.8,
    discount: 19,
    stock: 80,
    reviewCount: 5200,
    isDeal: true,
    isBestSeller: true,
    weight: '400',
    unit: 'g',
  ),
  Product(
    id: 'db_6',
    name: 'Amul Taaza UHT Milk 1L',
    brand: 'Amul',
    category: 'dairy_bread',
    subcategory: 'milk',
    description: 'Full fat UHT processed milk.',
    images: ['https://images.unsplash.com/photo-1563636619-e9143da7973b?w=500&auto=format&fit=crop&q=60'],
    tags: ['milk', 'amul', 'uht', 'dairy'],
    price: 68.0,
    mrp: 75.0,
    rating: 4.8,
    discount: 9,
    stock: 300,
    reviewCount: 15000,
    isDeal: false,
    isBestSeller: true,
    weight: '1',
    unit: 'L',
  ),

  // FRUITS & VEG (additional)
  Product(
    id: 'fv_8',
    name: 'Broccoli (1 Head ~350g)',
    brand: 'Fresh Farm',
    category: 'fruits_veg',
    subcategory: 'vegetables',
    description: 'Fresh green broccoli head.',
    images: ['https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?w=500&auto=format&fit=crop&q=60'],
    tags: ['broccoli', 'vegetable', 'fresh', 'green'],
    price: 55.0,
    mrp: 75.0,
    rating: 4.6,
    discount: 26,
    stock: 40,
    reviewCount: 890,
    isDeal: false,
    isBestSeller: false,
    weight: '350',
    unit: 'g',
  ),
  Product(
    id: 'fv_9',
    name: 'Alphonso Mango 6pcs',
    brand: 'Ratnagiri',
    category: 'fruits_veg',
    subcategory: 'fruits',
    description: 'Premium Alphonso mangoes from Ratnagiri.',
    images: ['https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?w=500&auto=format&fit=crop&q=60'],
    tags: ['mango', 'alphonso', 'fruit', 'summer'],
    price: 199.0,
    mrp: 280.0,
    rating: 4.9,
    discount: 28,
    stock: 30,
    reviewCount: 2100,
    isDeal: true,
    isBestSeller: true,
    weight: '6',
    unit: 'pcs',
  ),
  Product(
    id: 'fv_10',
    name: 'Watermelon (Whole ~3kg)',
    brand: 'Fresh Farm',
    category: 'fruits_veg',
    subcategory: 'fruits',
    description: 'Juicy whole watermelon.',
    images: ['https://images.unsplash.com/photo-1563114773-84221bd62daa?w=500&auto=format&fit=crop&q=60'],
    tags: ['watermelon', 'fruit', 'summer', 'fresh'],
    price: 59.0,
    mrp: 80.0,
    rating: 4.7,
    discount: 26,
    stock: 25,
    reviewCount: 1200,
    isDeal: true,
    isBestSeller: false,
    weight: '3',
    unit: 'kg',
  ),
];
