// search_keywords_data.dart
// Hinglish + Hindi + English search support data

class SearchUtils {
  /// Returns true if [input] contains any Devanagari (Hindi script) character
  static bool isHindiScript(String input) {
    for (final c in input.runes) {
      if (c >= 0x0900 && c <= 0x097F) return true;
    }
    return false;
  }

  /// Common Hinglish misspelling / alias → corrected search term
  static const Map<String, String> correctionMap = {
    'tamoto': 'tamatar',
    'tometo': 'tomato',
    'majji': 'maggi',
    'maagi': 'maggi',
    'magi': 'maggi',
    'biskit': 'biscuit',
    'biskut': 'biscuit',
    'biscit': 'biscuit',
    'sabun': 'soap',
    'sabon': 'soap',
    'tel': 'oil',
    'ghee': 'ghee',
    'dudh': 'milk',
    'doodh': 'milk',
    'makhan': 'butter',
    'anda': 'eggs',
    'anday': 'eggs',
    'andey': 'eggs',
    'sabzi': 'vegetables',
    'sabji': 'vegetables',
    'dawa': 'medicine',
    'dawai': 'medicine',
    'dawayi': 'medicine',
    'sham poo': 'shampoo',
    'chips': 'chips',
    'chipse': 'chips',
    'namkeen': 'snacks',
    'mithai': 'sweets',
    'mitha': 'sweets',
    'choclate': 'chocolate',
    'chocklate': 'chocolate',
    'joos': 'juice',
    'pani': 'water',
    'chawal': 'rice',
    'chaawal': 'rice',
    'aata': 'atta',
    'aatta': 'atta',
    'mosala': 'masala',
    'namak': 'salt',
    'cheeni': 'sugar',
    'shakkar': 'sugar',
    'pyaz': 'onion',
    'pyaaz': 'onion',
    'palak': 'spinach',
    'aam': 'mango',
    'tarbuj': 'watermelon',
    'tarbooz': 'watermelon',
    'roti': 'bread',
    'dahi': 'curd',
    'badam': 'almonds',
    'nashta': 'breakfast',
    'subah': 'morning',
    'murgi': 'chicken',
    'machli': 'fish',
    'machhi': 'fish',
    'gosht': 'mutton',
    'mombatti': 'candle',
    'paudha': 'plant',
  };

  /// Returns suggestion if input is a known alias/correction
  static String? getSuggestion(String input) {
    final lower = input.toLowerCase().trim();
    return correctionMap[lower];
  }

  /// Checks if the query partially matches any keyword (for local search)
  static bool matchesKeywords(Map<String, dynamic> product, String query) {
    final q = query.toLowerCase().trim();
    final keywords = [
      ...(product['searchKeywords'] as List<dynamic>? ?? []),
      ...(product['searchKeywordsHindi'] as List<dynamic>? ?? []),
    ].map((e) => e.toString().toLowerCase()).toList();

    // Check exact keyword match
    if (keywords.any((k) => k.contains(q))) return true;

    // Check title match
    final title = (product['title'] ?? product['name'] ?? '').toString().toLowerCase();
    return title.contains(q);
  }
}

/// Full local product catalog with Hinglish + Hindi search keywords
const List<Map<String, dynamic>> kLocalProducts = [
  {
    'id': 'local_tomato',
    'title': 'Fresh Tomatoes',
    'hindiName': 'ताजा टमाटर',
    'name': 'Fresh Tomatoes',
    'price': 35.0,
    'mrp': 50.0,
    'unit': '500 g',
    'image': 'https://cdn.pixabay.com/photo/2011/03/16/16/01/tomatoes-5356_1280.jpg',
    'isDeal': true,
    'isBestSeller': false,
    'discount': '30% OFF',
    'category': 'vacations',
    'categoryTags': ['vacations', 'vegetables'],
    'searchKeywords': [
      'tomato','tomatoes','tamatar','tamaatar','tamater','fresh tomato','lal tamatar',
      'sabzi','sabji','vegetable','red vegetable','grocery','taza sabzi','fresh sabzi','salad',
    ],
    'searchKeywordsHindi': ['टमाटर','ताजा टमाटर','लाल टमाटर','सब्जी','हरी सब्जी'],
  },
  {
    'id': 'local_capsicum',
    'title': 'Green Capsicum',
    'hindiName': 'हरी शिमला मिर्च',
    'name': 'Green Capsicum',
    'price': 40.0,
    'mrp': 55.0,
    'unit': '250 g',
    'image': 'https://cdn.pixabay.com/photo/2016/03/05/21/50/bell-peppers-1238094_1280.jpg',
    'isDeal': false,
    'isBestSeller': false,
    'discount': '',
    'category': 'vacations',
    'categoryTags': ['vacations', 'vegetables'],
    'searchKeywords': [
      'capsicum','shimla mirch','shimla','mirch','green capsicum','bell pepper','pepper',
      'sabzi','sabji','vegetable','green vegetable','hara','salad vegetable',
    ],
    'searchKeywordsHindi': ['शिमला मिर्च','हरी शिमला मिर्च','सब्जी','मिर्च'],
  },
  {
    'id': 'local_spinach',
    'title': 'Baby Spinach',
    'hindiName': 'पालक',
    'name': 'Baby Spinach',
    'price': 30.0,
    'mrp': 40.0,
    'unit': '200 g',
    'image': 'https://cdn.pixabay.com/photo/2016/07/11/15/19/spinach-1510418_1280.jpg',
    'isDeal': false,
    'isBestSeller': false,
    'discount': '',
    'category': 'vacations',
    'categoryTags': ['vacations', 'vegetables'],
    'searchKeywords': [
      'spinach','palak','baby spinach','green leafy','leafy vegetable','hara sabzi',
      'palak sabzi','fresh palak','healthy vegetable','iron vegetable','saag',
    ],
    'searchKeywordsHindi': ['पालक','हरा साग','साग','पत्तेदार सब्जी'],
  },
  {
    'id': 'local_onion',
    'title': 'Red Onions',
    'hindiName': 'लाल प्याज',
    'name': 'Red Onions',
    'price': 25.0,
    'mrp': 35.0,
    'unit': '1 kg',
    'image': 'https://cdn.pixabay.com/photo/2016/08/11/08/04/onions-1585060_1280.jpg',
    'isDeal': true,
    'isBestSeller': true,
    'discount': '28% OFF',
    'category': 'vacations',
    'categoryTags': ['vacations', 'vegetables'],
    'searchKeywords': [
      'onion','pyaz','pyaaz','red onion','lal pyaz','sabzi','cooking essential',
      'kitchen essential','masala','tadka','fry','base vegetable',
    ],
    'searchKeywordsHindi': ['प्याज','लाल प्याज','कांदा','सब्जी','मसाला'],
  },
  {
    'id': 'local_mango',
    'title': 'Alphonso Mango',
    'hindiName': 'अल्फांसो आम',
    'name': 'Alphonso Mango',
    'price': 199.0,
    'mrp': 250.0,
    'unit': '1 kg',
    'image': 'https://cdn.pixabay.com/photo/2018/08/08/17/32/mango-3592485_1280.jpg',
    'isDeal': true,
    'isBestSeller': true,
    'discount': '20% OFF',
    'category': 'vacations',
    'categoryTags': ['vacations', 'fruits'],
    'searchKeywords': [
      'mango','aam','alphonso','hapus','aamras','fruit','mitha phal','seasonal fruit',
      'summer fruit','yellow fruit','king of fruits','meetha aam',
    ],
    'searchKeywordsHindi': ['आम','अल्फांसो','फल','रसीला आम','मीठा आम','केरी'],
  },
  {
    'id': 'local_watermelon',
    'title': 'Watermelon',
    'hindiName': 'तरबूज',
    'name': 'Watermelon',
    'price': 49.0,
    'mrp': 65.0,
    'unit': '1 pc (approx 3kg)',
    'image': 'https://cdn.pixabay.com/photo/2016/07/22/10/16/watermelon-1534272_1280.jpg',
    'isDeal': true,
    'isBestSeller': false,
    'discount': '24% OFF',
    'category': 'vacations',
    'categoryTags': ['vacations', 'fruits'],
    'searchKeywords': [
      'watermelon','tarbuj','tarbooz','summer fruit','red fruit','pani wala fruit',
      'bada fruit','mithas','thanda fruit','seasonal',
    ],
    'searchKeywordsHindi': ['तरबूज','फल','गर्मी का फल','रसीला फल'],
  },
  {
    'id': 'local_atta',
    'title': 'Aashirvaad Atta 5kg',
    'hindiName': 'आशीर्वाद आटा',
    'name': 'Aashirvaad Atta 5kg',
    'price': 270.0,
    'mrp': 310.0,
    'unit': '5 kg',
    'image': 'https://cdn.pixabay.com/photo/2014/11/05/15/57/bag-518013_1280.jpg',
    'isDeal': true,
    'isBestSeller': true,
    'discount': '13% OFF',
    'category': 'grocery_kitchen',
    'categoryTags': ['grocery_kitchen', 'staples'],
    'searchKeywords': [
      'atta','aata','gehun ka aata','wheat','wheat flour','chakki atta','roti atta',
      'chapati atta','aashirvaad','flour','gehun','roti flour','whole wheat',
      'multigrain atta','taza atta',
    ],
    'searchKeywordsHindi': ['आटा','गेहूं का आटा','चक्की आटा','रोटी आटा','गेहूं','आशीर्वाद आटा'],
  },
  {
    'id': 'local_rice',
    'title': 'India Gate Basmati Rice',
    'hindiName': 'इंडिया गेट चावल',
    'name': 'India Gate Basmati Rice',
    'price': 185.0,
    'mrp': 210.0,
    'unit': '1 kg',
    'image': 'https://cdn.pixabay.com/photo/2018/05/13/19/55/rice-3397599_1280.jpg',
    'isDeal': true,
    'isBestSeller': false,
    'discount': '12% OFF',
    'category': 'grocery_kitchen',
    'categoryTags': ['grocery_kitchen', 'staples'],
    'searchKeywords': [
      'rice','chawal','basmati','basmati chawal','india gate','long grain',
      'biryani chawal','pulao chawal','white rice','steam chawal','khichdi chawal',
      'sella rice','parimal rice','chaawal',
    ],
    'searchKeywordsHindi': ['चावल','बासमती चावल','इंडिया गेट','बिरयानी चावल','पुलाव'],
  },
  {
    'id': 'local_dal',
    'title': 'Tata Sampann Moong Dal',
    'hindiName': 'मूंग दाल',
    'name': 'Tata Sampann Moong Dal',
    'price': 120.0,
    'mrp': 140.0,
    'unit': '500 g',
    'image': 'https://cdn.pixabay.com/photo/2017/02/24/03/25/dal-2093959_1280.jpg',
    'isDeal': false,
    'isBestSeller': false,
    'discount': '',
    'category': 'grocery_kitchen',
    'categoryTags': ['grocery_kitchen', 'staples'],
    'searchKeywords': [
      'dal','moong dal','moong','tata sampann','lentil','yellow dal','sabut moong',
      'dhuli moong','protein','khichdi dal','dal chawal','daal','sabut dal','split dal',
    ],
    'searchKeywordsHindi': ['मूंग दाल','दाल','धुली दाल','साबुत मूंग','टाटा सम्पन्न'],
  },
  {
    'id': 'local_oil',
    'title': 'Fortune Sunflower Oil',
    'hindiName': 'फॉर्च्यून तेल',
    'name': 'Fortune Sunflower Oil',
    'price': 145.0,
    'mrp': 165.0,
    'unit': '1 L',
    'image': 'https://cdn.pixabay.com/photo/2015/01/15/13/02/sunflower-oil-599731_1280.jpg',
    'isDeal': true,
    'isBestSeller': false,
    'discount': '12% OFF',
    'category': 'grocery_kitchen',
    'categoryTags': ['grocery_kitchen'],
    'searchKeywords': [
      'oil','tel','sunflower oil','surajmukhi tel','cooking oil','refined oil','fortune',
      'khana pakane ka tel','frying oil','vegetable oil','sarson tel','tel ghee',
    ],
    'searchKeywordsHindi': ['तेल','सूरजमुखी तेल','खाना पकाने का तेल','रिफाइंड तेल','फॉर्च्यून'],
  },
  {
    'id': 'local_ghee',
    'title': 'Amul Pure Ghee',
    'hindiName': 'अमूल घी',
    'name': 'Amul Pure Ghee',
    'price': 560.0,
    'mrp': 620.0,
    'unit': '500 ml',
    'image': 'https://cdn.pixabay.com/photo/2020/02/01/21/37/ghee-4810540_1280.jpg',
    'isDeal': true,
    'isBestSeller': true,
    'discount': '10% OFF',
    'category': 'grocery_kitchen',
    'categoryTags': ['grocery_kitchen', 'dairy'],
    'searchKeywords': [
      'ghee','desi ghee','amul ghee','pure ghee','cow ghee','makhan ghee','cooking ghee',
      'tadka ghee','dal ghee','roti ghee','clarified butter','asli ghee','shudh ghee',
    ],
    'searchKeywordsHindi': ['घी','देसी घी','अमूल घी','शुद्ध घी','असली घी','गाय का घी'],
  },
  {
    'id': 'local_masala',
    'title': 'MDH Garam Masala',
    'hindiName': 'एमडीएच गरम मसाला',
    'name': 'MDH Garam Masala',
    'price': 85.0,
    'mrp': 100.0,
    'unit': '100 g',
    'image': 'https://cdn.pixabay.com/photo/2016/05/19/11/27/masala-1402657_1280.jpg',
    'isDeal': false,
    'isBestSeller': false,
    'discount': '',
    'category': 'grocery_kitchen',
    'categoryTags': ['grocery_kitchen'],
    'searchKeywords': [
      'masala','garam masala','mdh','spice','spices','cooking masala','curry masala',
      'khana masala','whole spice','masale','indian masala','mdh masala','biryani masala',
    ],
    'searchKeywordsHindi': ['गरम मसाला','मसाला','एमडीएच मसाला','खाना मसाला','मसाले'],
  },
  {
    'id': 'local_milk',
    'title': 'Amul Taaza Milk',
    'hindiName': 'अमूल ताज़ा दूध',
    'name': 'Amul Taaza Milk',
    'price': 62.0,
    'mrp': 65.0,
    'unit': '1 L',
    'image': 'https://cdn.pixabay.com/photo/2017/07/05/15/41/milk-2474993_1280.jpg',
    'isDeal': false,
    'isBestSeller': true,
    'discount': '',
    'category': 'grocery_kitchen',
    'categoryTags': ['grocery_kitchen', 'dairy'],
    'searchKeywords': [
      'milk','dudh','amul','taaza','toned milk','packet dudh','safed dudh','gai ka dudh',
      'cow milk','dairy','fresh milk','subah ka dudh','dudh packet','amul dudh','taza dudh',
      'doodh',
    ],
    'searchKeywordsHindi': ['दूध','अमूल दूध','ताज़ा दूध','गाय का दूध','पैकेट दूध','टोन्ड दूध'],
  },
  {
    'id': 'local_butter',
    'title': 'Amul Butter',
    'hindiName': 'अमूल मक्खन',
    'name': 'Amul Butter',
    'price': 56.0,
    'mrp': 60.0,
    'unit': '100 g',
    'image': 'https://cdn.pixabay.com/photo/2016/04/11/17/47/butter-1322649_1280.jpg',
    'isDeal': false,
    'isBestSeller': true,
    'discount': '',
    'category': 'grocery_kitchen',
    'categoryTags': ['grocery_kitchen', 'dairy'],
    'searchKeywords': [
      'butter','makhan','amul butter','amul makhan','salted butter','bread butter',
      'toast butter','cooking butter','white makhan','desi makhan','fat','dairy product',
      'roti makhan',
    ],
    'searchKeywordsHindi': ['मक्खन','अमूल मक्खन','सफेद मक्खन','देसी मक्खन','ब्रेड मक्खन'],
  },
  {
    'id': 'local_bread',
    'title': 'Britannia Bread',
    'hindiName': 'ब्रिटानिया ब्रेड',
    'name': 'Britannia Bread',
    'price': 42.0,
    'mrp': 45.0,
    'unit': '400 g',
    'image': 'https://cdn.pixabay.com/photo/2014/07/22/09/59/bread-399286_1280.jpg',
    'isDeal': false,
    'isBestSeller': false,
    'discount': '',
    'category': 'grocery_kitchen',
    'categoryTags': ['grocery_kitchen'],
    'searchKeywords': [
      'bread','double roti','sandwich bread','brown bread','white bread','britannia',
      'loaf','toast bread','multigrain bread','bread loaf','breakfast',
    ],
    'searchKeywordsHindi': ['डबल रोटी','ब्रेड','सैंडविच ब्रेड','ब्राउन ब्रेड','टोस्ट ब्रेड'],
  },
  {
    'id': 'local_eggs',
    'title': 'Farm Fresh Eggs',
    'hindiName': 'ताजा अंडे',
    'name': 'Farm Fresh Eggs',
    'price': 84.0,
    'mrp': 90.0,
    'unit': '6 pcs',
    'image': 'https://cdn.pixabay.com/photo/2017/08/11/22/28/egg-2631375_1280.jpg',
    'isDeal': false,
    'isBestSeller': true,
    'discount': '',
    'category': 'grocery_kitchen',
    'categoryTags': ['grocery_kitchen'],
    'searchKeywords': [
      'eggs','anda','anday','farm eggs','fresh eggs','brown eggs','white eggs','desi anda',
      'protein','breakfast anda','boiled egg','omelette anda','egg tray','dozen eggs','andey',
    ],
    'searchKeywordsHindi': ['अंडा','अंडे','फार्म अंडे','देसी अंडा','ताजा अंडा','उबला अंडा'],
  },
  {
    'id': 'local_curd',
    'title': 'Mother Dairy Curd',
    'hindiName': 'मदर डेयरी दही',
    'name': 'Mother Dairy Curd',
    'price': 28.0,
    'mrp': 32.0,
    'unit': '400 g',
    'image': 'https://cdn.pixabay.com/photo/2017/09/01/19/55/greek-2704466_1280.jpg',
    'isDeal': false,
    'isBestSeller': false,
    'discount': '',
    'category': 'grocery_kitchen',
    'categoryTags': ['grocery_kitchen', 'dairy'],
    'searchKeywords': [
      'curd','dahi','yogurt','mother dairy','taza dahi','mishti doi','plain curd',
      'set dahi','raita dahi','fresh dahi','dudh dahi','creamy dahi','sweet curd','lassi dahi',
    ],
    'searchKeywordsHindi': ['दही','ताजा दही','मदर डेयरी दही','मिष्टी दोई','रायता'],
  },
  {
    'id': 'local_parleg',
    'title': 'Parle G Biscuits',
    'hindiName': 'पारले जी बिस्कुट',
    'name': 'Parle G Biscuits',
    'price': 10.0,
    'mrp': 10.0,
    'unit': '100 g',
    'image': 'https://cdn.pixabay.com/photo/2015/10/26/09/09/cookie-1006723_1280.jpg',
    'isDeal': false,
    'isBestSeller': true,
    'discount': '',
    'category': 'snacks_drinks',
    'categoryTags': ['snacks_drinks', 'biscuits'],
    'searchKeywords': [
      'parle g','biscuit','biskut','glucose biscuit','chai biscuit','parle','tea time biscuit',
      'snack','glucose','cheap biscuit','bachpan biscuit','yellow packet','kids biscuit',
    ],
    'searchKeywordsHindi': ['बिस्कुट','पारले जी','ग्लूकोज बिस्कुट','चाय बिस्कुट','नाश्ता'],
  },
  {
    'id': 'local_oreo',
    'title': 'Oreo Chocolate Cream',
    'hindiName': 'ओरियो बिस्कुट',
    'name': 'Oreo Chocolate Cream',
    'price': 30.0,
    'mrp': 35.0,
    'unit': '120 g',
    'image': 'https://cdn.pixabay.com/photo/2016/11/29/10/32/cookies-1869660_1280.jpg',
    'isDeal': false,
    'isBestSeller': true,
    'discount': '',
    'category': 'snacks_drinks',
    'categoryTags': ['snacks_drinks', 'biscuits'],
    'searchKeywords': [
      'oreo','chocolate biscuit','cream biscuit','oreo biscuit','dark biscuit',
      'sandwich biscuit','nabisco','twist lick dunk','chocolate cream','cookies','cookie',
      'meetha biscuit','biskut',
    ],
    'searchKeywordsHindi': ['ओरियो','चॉकलेट बिस्कुट','क्रीम बिस्कुट','मीठा बिस्कुट'],
  },
  {
    'id': 'local_maggi',
    'title': 'Maggi Noodles',
    'hindiName': 'मैगी नूडल्स',
    'name': 'Maggi Noodles',
    'price': 14.0,
    'mrp': 14.0,
    'unit': '70 g',
    'image': 'https://cdn.pixabay.com/photo/2015/03/26/09/47/udon-690048_1280.jpg',
    'isDeal': false,
    'isBestSeller': true,
    'discount': '',
    'category': 'snacks_drinks',
    'categoryTags': ['snacks_drinks'],
    'searchKeywords': [
      'maggi','noodles','noodle','instant noodles','2 minute noodles','masala maggi',
      'maggi masala','fast food','quick snack','bachon ka khana','evening snack',
      'supper','pasta maggi','cup noodles','do minute noodle',
    ],
    'searchKeywordsHindi': ['मैगी','नूडल्स','इंस्टेंट नूडल्स','दो मिनट नूडल्स','मसाला मैगी'],
  },
  {
    'id': 'local_almonds',
    'title': 'Happilo Almonds',
    'hindiName': 'बादाम',
    'name': 'Happilo Almonds',
    'price': 280.0,
    'mrp': 320.0,
    'unit': '200 g',
    'image': 'https://cdn.pixabay.com/photo/2016/03/05/22/02/almond-1238168_1280.jpg',
    'isDeal': true,
    'isBestSeller': false,
    'discount': '12% OFF',
    'category': 'snacks_drinks',
    'categoryTags': ['snacks_drinks'],
    'searchKeywords': [
      'almonds','badam','dry fruit','badam giri','soaked badam','raw almonds',
      'roasted badam','healthy snack','protein snack','dry fruits','premium badam',
      'california badam',
    ],
    'searchKeywordsHindi': ['बादाम','ड्राई फ्रूट','भीगे बादाम','स्वस्थ नाश्ता'],
  },
  {
    'id': 'local_cornflakes',
    'title': 'Kelloggs Corn Flakes',
    'hindiName': 'कॉर्नफ्लेक्स',
    'name': 'Kelloggs Corn Flakes',
    'price': 185.0,
    'mrp': 210.0,
    'unit': '500 g',
    'image': 'https://cdn.pixabay.com/photo/2015/04/10/07/28/corn-714569_1280.jpg',
    'isDeal': false,
    'isBestSeller': false,
    'discount': '',
    'category': 'snacks_drinks',
    'categoryTags': ['snacks_drinks'],
    'searchKeywords': [
      'corn flakes','cornflakes','kelloggs','cereal','breakfast cereal','nashta',
      'subah ka nashta','healthy breakfast','milk cereal','crunchy cereal',
      'morning cereal','diet food',
    ],
    'searchKeywordsHindi': ['कॉर्नफ्लेक्स','केलॉग्स','नाश्ता','सुबह का नाश्ता'],
  },
  {
    'id': 'local_lays',
    'title': 'Lays Chips',
    'hindiName': 'लेज़ चिप्स',
    'name': 'Lays Chips',
    'price': 20.0,
    'mrp': 20.0,
    'unit': '50 g',
    'image': 'https://cdn.pixabay.com/photo/2016/09/26/16/43/chips-1696395_1280.jpg',
    'isDeal': false,
    'isBestSeller': true,
    'discount': '',
    'category': 'snacks_drinks',
    'categoryTags': ['snacks_drinks'],
    'searchKeywords': [
      'lays','chips','potato chips','cream onion lays','masala lays','crisps',
      'packet chips','fried chips','snack','namkeen','timepass','party snack',
      'munchies','lays classic',
    ],
    'searchKeywordsHindi': ['लेज़','चिप्स','आलू चिप्स','नमकीन','टाइमपास','पार्टी स्नैक'],
  },
  {
    'id': 'local_kurkure',
    'title': 'Kurkure',
    'hindiName': 'कुरकुरे',
    'name': 'Kurkure',
    'price': 20.0,
    'mrp': 20.0,
    'unit': '90 g',
    'image': 'https://cdn.pixabay.com/photo/2021/01/08/16/17/chips-5899655_1280.jpg',
    'isDeal': false,
    'isBestSeller': true,
    'discount': '',
    'category': 'snacks_drinks',
    'categoryTags': ['snacks_drinks'],
    'searchKeywords': [
      'kurkure','namkeen','masala namkeen','crunchy namkeen','corn namkeen',
      'spicy snack','evening snack','timepass','desi snack','hot snack','tangy snack',
      'tea time snack',
    ],
    'searchKeywordsHindi': ['कुरकुरे','नमकीन','मसाला नमकीन','कुरकुरा नाश्ता'],
  },
  {
    'id': 'local_bhujia',
    'title': 'Haldirams Aloo Bhujia',
    'hindiName': 'हल्दीराम भुजिया',
    'name': 'Haldirams Aloo Bhujia',
    'price': 60.0,
    'mrp': 70.0,
    'unit': '200 g',
    'image': 'https://cdn.pixabay.com/photo/2020/03/17/20/21/snack-4940810_1280.jpg',
    'isDeal': false,
    'isBestSeller': true,
    'discount': '',
    'category': 'snacks_drinks',
    'categoryTags': ['snacks_drinks'],
    'searchKeywords': [
      'haldirams','bhujia','aloo bhujia','namkeen','haldiram','sev','bikaner bhujia',
      'rajasthani namkeen','spicy namkeen','chai namkeen','snack','dry namkeen','mixture',
    ],
    'searchKeywordsHindi': ['हल्दीराम','भुजिया','आलू भुजिया','नमकीन'],
  },
  {
    'id': 'local_cadbury',
    'title': 'Cadbury Dairy Milk',
    'hindiName': 'कैडबरी डेयरी मिल्क',
    'name': 'Cadbury Dairy Milk',
    'price': 40.0,
    'mrp': 45.0,
    'unit': '36 g',
    'image': 'https://cdn.pixabay.com/photo/2016/11/09/06/05/chocolate-1810644_1280.jpg',
    'isDeal': false,
    'isBestSeller': true,
    'discount': '',
    'category': 'snacks_drinks',
    'categoryTags': ['snacks_drinks'],
    'searchKeywords': [
      'cadbury','dairy milk','chocolate','choco','meetha','dark chocolate','milk chocolate',
      'cadbury chocolate','silk chocolate','birthday chocolate','gifting chocolate',
      'bar chocolate','mithai chocolate',
    ],
    'searchKeywordsHindi': ['कैडबरी','चॉकलेट','मीठा','डेयरी मिल्क','चॉकलेट बार'],
  },
  {
    'id': 'local_tropicana',
    'title': 'Tropicana Orange Juice',
    'hindiName': 'ट्रॉपिकाना जूस',
    'name': 'Tropicana Orange Juice',
    'price': 99.0,
    'mrp': 120.0,
    'unit': '1 L',
    'image': 'https://cdn.pixabay.com/photo/2017/05/11/19/44/fresh-squeezed-2305198_1280.jpg',
    'isDeal': true,
    'isBestSeller': false,
    'discount': '17% OFF',
    'category': 'snacks_drinks',
    'categoryTags': ['snacks_drinks'],
    'searchKeywords': [
      'juice','orange juice','tropicana','fruit juice','santra juice','narangi juice',
      'vitamin c juice','morning juice','fresh juice','packaged juice','breakfast juice',
      'cold juice','joos',
    ],
    'searchKeywordsHindi': ['जूस','संतरे का जूस','फलों का जूस','ट्रॉपिकाना','सुबह का जूस'],
  },
  {
    'id': 'local_redbull',
    'title': 'Red Bull Energy Drink',
    'hindiName': 'रेड बुल',
    'name': 'Red Bull Energy Drink',
    'price': 115.0,
    'mrp': 125.0,
    'unit': '250 ml',
    'image': 'https://cdn.pixabay.com/photo/2013/07/25/16/58/red-bull-167218_1280.jpg',
    'isDeal': false,
    'isBestSeller': true,
    'discount': '',
    'category': 'snacks_drinks',
    'categoryTags': ['snacks_drinks'],
    'searchKeywords': [
      'red bull','energy drink','energy','boost drink','caffeinated drink','redbull',
      'wings drink','late night drink','study drink','gym drink','workout drink','can drink',
    ],
    'searchKeywordsHindi': ['रेड बुल','एनर्जी ड्रिंक','बूस्ट ड्रिंक','ताकत पेय'],
  },
  {
    'id': 'local_nivea',
    'title': 'Nivea Soft Cream',
    'hindiName': 'निविया क्रीम',
    'name': 'Nivea Soft Cream',
    'price': 120.0,
    'mrp': 145.0,
    'unit': '200 ml',
    'image': 'https://cdn.pixabay.com/photo/2015/01/21/14/14/cream-606474_1280.jpg',
    'isDeal': true,
    'isBestSeller': false,
    'discount': '17% OFF',
    'category': 'beauty',
    'categoryTags': ['beauty'],
    'searchKeywords': [
      'nivea','moisturizer','cream','face cream','body cream','moisturising cream',
      'skin cream','soft skin','winter cream','dry skin cream','nourishing cream',
      'lotion','hand cream',
    ],
    'searchKeywordsHindi': ['निविया','मॉइस्चराइज़र','फेस क्रीम','त्वचा क्रीम','बॉडी लोशन'],
  },
  {
    'id': 'local_pantene',
    'title': 'Pantene Shampoo',
    'hindiName': 'पेंटीन शैम्पू',
    'name': 'Pantene Shampoo',
    'price': 180.0,
    'mrp': 210.0,
    'unit': '340 ml',
    'image': 'https://cdn.pixabay.com/photo/2019/10/12/08/12/shampoo-4544032_1280.jpg',
    'isDeal': true,
    'isBestSeller': true,
    'discount': '14% OFF',
    'category': 'beauty',
    'categoryTags': ['beauty'],
    'searchKeywords': [
      'shampoo','pantene','baal ka shampoo','hair shampoo','smooth shampoo',
      'hair wash','baal dhona','hair care','silky hair','anti dandruff shampoo',
      'hair fall shampoo','sham',
    ],
    'searchKeywordsHindi': ['शैम्पू','पेंटीन','बालों का शैम्पू','बाल धोना','रूसी शैम्पू'],
  },
  {
    'id': 'local_kajal',
    'title': 'Lakme Kajal',
    'hindiName': 'काजल',
    'name': 'Lakme Kajal',
    'price': 145.0,
    'mrp': 165.0,
    'unit': '0.35 g',
    'image': 'https://cdn.pixabay.com/photo/2020/06/13/20/49/eye-5295974_1280.jpg',
    'isDeal': false,
    'isBestSeller': true,
    'discount': '',
    'category': 'beauty',
    'categoryTags': ['beauty'],
    'searchKeywords': [
      'kajal','kohl','eye kajal','lakme kajal','black kajal','aankhon ka kajal',
      'eye liner','eye makeup','waterproof kajal','smudge proof kajal','dark kajal','makeup',
    ],
    'searchKeywordsHindi': ['काजल','आंखों का काजल','लैक्मे काजल','आई लाइनर','मेकअप'],
  },
  {
    'id': 'local_soap',
    'title': 'Dove Soap',
    'hindiName': 'डव साबुन',
    'name': 'Dove Soap',
    'price': 50.0,
    'mrp': 58.0,
    'unit': '100 g',
    'image': 'https://cdn.pixabay.com/photo/2017/08/01/01/33/soap-2562182_1280.jpg',
    'isDeal': false,
    'isBestSeller': true,
    'discount': '',
    'category': 'beauty',
    'categoryTags': ['beauty'],
    'searchKeywords': [
      'soap','sabun','dove soap','bathing soap','body wash soap','moisturising soap',
      'skin soap','naha dhona','bathing bar','shower soap','daily soap','white soap',
      'creamy soap',
    ],
    'searchKeywordsHindi': ['साबुन','डव','नहाने का साबुन','मॉइस्चराइज़िंग साबुन','त्वचा देखभाल'],
  },
  {
    'id': 'local_fogg',
    'title': 'Fogg Perfume',
    'hindiName': 'फॉग डियो',
    'name': 'Fogg Perfume',
    'price': 195.0,
    'mrp': 225.0,
    'unit': '150 ml',
    'image': 'https://cdn.pixabay.com/photo/2020/07/17/14/53/perfume-5413778_1280.jpg',
    'isDeal': true,
    'isBestSeller': false,
    'discount': '13% OFF',
    'category': 'beauty',
    'categoryTags': ['beauty'],
    'searchKeywords': [
      'perfume','deo','deodorant','fogg','body spray','scent','fragrance','mehak',
      'khushbu','mens deo','ladies deo','long lasting perfume','daily deo','spray perfume',
    ],
    'searchKeywordsHindi': ['परफ्यूम','डियोडोरेंट','बॉडी स्प्रे','खुशबू','महक','फॉग'],
  },
  {
    'id': 'local_toothpaste',
    'title': 'Colgate Toothpaste',
    'hindiName': 'कोलगेट टूथपेस्ट',
    'name': 'Colgate Toothpaste',
    'price': 95.0,
    'mrp': 110.0,
    'unit': '200 g',
    'image': 'https://cdn.pixabay.com/photo/2020/01/21/20/08/toothbrush-4982682_1280.jpg',
    'isDeal': false,
    'isBestSeller': true,
    'discount': '',
    'category': 'beauty',
    'categoryTags': ['beauty'],
    'searchKeywords': [
      'toothpaste','paste','colgate','dant manjan','dant saaf','teeth paste',
      'cavity paste','strong teeth paste','whitening paste','daily paste',
      'brushing paste','mint paste',
    ],
    'searchKeywordsHindi': ['कोलगेट','टूथपेस्ट','दांत मंजन','दांत साफ','दंत देखभाल'],
  },
  {
    'id': 'local_ariel',
    'title': 'Ariel Matic Detergent',
    'hindiName': 'एरियल डिटर्जेंट',
    'name': 'Ariel Matic Detergent',
    'price': 260.0,
    'mrp': 295.0,
    'unit': '1 kg',
    'image': 'https://cdn.pixabay.com/photo/2017/03/12/01/23/washing-powder-2136542_1280.jpg',
    'isDeal': true,
    'isBestSeller': false,
    'discount': '12% OFF',
    'category': 'beauty',
    'categoryTags': ['beauty'],
    'searchKeywords': [
      'ariel','detergent','washing powder','kapde dhona','laundry powder',
      'washing machine powder','clothes wash','kapdon ka powder','matic detergent',
      'liquid detergent',
    ],
    'searchKeywordsHindi': ['एरियल','डिटर्जेंट','वॉशिंग पाउडर','कपड़े धोना','लॉन्ड्री'],
  },
  {
    'id': 'local_lizol',
    'title': 'Lizol Floor Cleaner',
    'hindiName': 'लिज़ॉल फ्लोर क्लीनर',
    'name': 'Lizol Floor Cleaner',
    'price': 110.0,
    'mrp': 130.0,
    'unit': '500 ml',
    'image': 'https://cdn.pixabay.com/photo/2015/01/09/09/36/mop-594177_1280.jpg',
    'isDeal': false,
    'isBestSeller': false,
    'discount': '',
    'category': 'beauty',
    'categoryTags': ['beauty'],
    'searchKeywords': [
      'lizol','floor cleaner','phenyl','floor wash','pocha','mopping liquid',
      'cleaning liquid','floor liquid','toilet cleaner','bathroom cleaner',
      'pine cleaner','floor disinfectant',
    ],
    'searchKeywordsHindi': ['लिज़ॉल','फ्लोर क्लीनर','फिनाइल','पोछा','सफाई'],
  },
  {
    'id': 'local_crocin',
    'title': 'Crocin Tablet',
    'hindiName': 'क्रोसिन टैबलेट',
    'name': 'Crocin Tablet',
    'price': 30.0,
    'mrp': 35.0,
    'unit': '15 tablets',
    'image': 'https://cdn.pixabay.com/photo/2020/02/06/23/10/medicine-4825451_1280.jpg',
    'isDeal': false,
    'isBestSeller': true,
    'discount': '',
    'category': 'pharmacy',
    'categoryTags': ['pharmacy'],
    'searchKeywords': [
      'crocin','paracetamol','dawa','medicine','pain relief','tablet','fever tablet',
      'sar dard','headache tablet','bukhar ki dawa','body pain tablet','cold tablet',
      'flu tablet','dawai',
    ],
    'searchKeywordsHindi': ['दवा','क्रोसिन','पैरासिटामोल','सिरदर्द','बुखार की दवा','दर्द निवारक'],
  },
  {
    'id': 'local_pampers',
    'title': 'Pampers Diapers',
    'hindiName': 'पैम्पर्स डायपर',
    'name': 'Pampers Diapers',
    'price': 399.0,
    'mrp': 450.0,
    'unit': '40 pcs',
    'image': 'https://cdn.pixabay.com/photo/2016/08/08/09/17/baby-1578149_1280.jpg',
    'isDeal': true,
    'isBestSeller': true,
    'discount': '11% OFF',
    'category': 'pharmacy',
    'categoryTags': ['pharmacy'],
    'searchKeywords': [
      'pampers','diaper','nappy','baby diaper','bacche ka diaper','pant diaper',
      'newborn diaper','soft diaper','dry diaper','leak proof diaper','baby care',
      'infant care',
    ],
    'searchKeywordsHindi': ['डायपर','पैम्पर्स','बच्चे का डायपर','नैपी','शिशु देखभाल'],
  },
  {
    'id': 'local_boat',
    'title': 'boAt Rockerz Headphones',
    'hindiName': 'बोट हेडफोन',
    'name': 'boAt Rockerz Headphones',
    'price': 1299.0,
    'mrp': 2999.0,
    'unit': '1 pc',
    'image': 'https://cdn.pixabay.com/photo/2018/09/17/14/27/headphones-3683983_1280.jpg',
    'isDeal': true,
    'isBestSeller': true,
    'discount': '57% OFF',
    'category': 'electronics',
    'categoryTags': ['electronics'],
    'searchKeywords': [
      'boat','headphones','earphones','bluetooth headphone','wireless headphone',
      'music headphone','over ear headphone','bass headphone','gaming headphone',
      'headset','boat rockerz','charger','bijli',
    ],
    'searchKeywordsHindi': ['बोट','हेडफोन','ईयरफोन','ब्लूटूथ','वायरलेस','संगीत'],
  },
  {
    'id': 'local_lego',
    'title': 'LEGO Classic Bricks',
    'hindiName': 'लेगो ब्लॉक्स',
    'name': 'LEGO Classic Bricks',
    'price': 1999.0,
    'mrp': 2499.0,
    'unit': '1 set',
    'image': 'https://cdn.pixabay.com/photo/2018/07/27/20/21/lego-3566246_1280.jpg',
    'isDeal': true,
    'isBestSeller': false,
    'discount': '20% OFF',
    'category': 'electronics',
    'categoryTags': ['electronics'],
    'searchKeywords': [
      'lego','blocks','building blocks','toy blocks','kids toy','creative toy',
      'construction toy','plastic blocks','lego set','lego classic','puzzle toy',
      'assembly toy','brain toy','khilona',
    ],
    'searchKeywordsHindi': ['लेगो','ब्लॉक्स','खिलौना','बच्चों का खिलौना','निर्माण खिलौना'],
  },
  {
    'id': 'local_cadbury_celebration',
    'title': 'Cadbury Celebrations Box',
    'hindiName': 'कैडबरी उपहार बॉक्स',
    'name': 'Cadbury Celebrations Box',
    'price': 399.0,
    'mrp': 450.0,
    'unit': '186 g',
    'image': 'https://cdn.pixabay.com/photo/2020/01/14/14/11/love-4765430_1280.jpg',
    'isDeal': false,
    'isBestSeller': true,
    'discount': '',
    'category': 'snacks_drinks',
    'categoryTags': ['snacks_drinks'],
    'searchKeywords': [
      'cadbury','celebration','gift box','chocolate gift','diwali gift','festival gift',
      'chocolate hamper','meetha gift','birthday gift','chocolate box','gifting',
      'party gift','tyohar gift',
    ],
    'searchKeywordsHindi': ['कैडबरी','उपहार बॉक्स','चॉकलेट उपहार','दिवाली उपहार','त्योहार उपहार'],
  },
];
